/**
 * Erasures DDD Dependencies - Composition root
 *
 * Generated by Dependencies Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: erasures
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * Erasures Domain Module - Composition root
 *
 * DDD: Composition root for erasures domain. Exposes repos (ports) and use cases
 * grouped by aggregate. No orgId at build time — use execution context at call time.
 */

import {
  ErasureDrillRepositoryAdapter,
  ErasureRepositoryAdapter,
} from "@offhash/adapters/erasures";
import { getIdGeneratorService } from "@offhash/adapters";
import type { AdapterDynamoDBClient } from "@offhash/adapters";
import { executionContextService } from "../../../lib/execution-context.service.js";
// Use-case constructors (concrete)
import {
  ExecuteCreateErasureDrill,
  ExecuteExecutePdErasure,
  ExecuteGetErasureDrill,
  ExecuteGetErasureJob,
  ExecuteListErasureDrills,
  ExecuteListErasureJobs,
} from "@offhash/services/erasures/usecases";
// Ports (interfaces)
import type {
  ErasureDrillRepository,
  ErasureRepository,
} from "@offhash/services/erasures/ports";

export interface ErasuresDomainModule {
  repos: {
    erasureDrills: ErasureDrillRepository;
    erasures: ErasureRepository;
  };
  useCases: {
    erasureDrills: {
      create: ExecuteCreateErasureDrill;
      get: ExecuteGetErasureDrill;
      list: ExecuteListErasureDrills;
    };
    erasures: {
      create: ExecuteExecutePdErasure;
      get: ExecuteGetErasureJob;
      list: ExecuteListErasureJobs;
    };
  };
}

export function buildErasuresDomainModule(
  dynamoClient: AdapterDynamoDBClient,
): ErasuresDomainModule {
  // Adapters implementing ports (adapters encapsulate Ddb)
  const repos = (() => {
    const obj: {
      erasureDrills?: ErasureDrillRepository;
      erasures?: ErasureRepository;
    } = {};

    obj.erasureDrills = new ErasureDrillRepositoryAdapter(dynamoClient);
    obj.erasures = new ErasureRepositoryAdapter(dynamoClient);
    return {
      erasureDrills: obj.erasureDrills!,
      erasures: obj.erasures!,
    };
  })();

  const executionContext = executionContextService;
  const idGenerator = getIdGeneratorService();

  // Use cases depend only on ports (repos.*)
  const useCases = {
    erasureDrills: {
      create: new ExecuteCreateErasureDrill(executionContext, idGenerator, repos.erasureDrills),
      get: new ExecuteGetErasureDrill(executionContext, idGenerator, repos.erasureDrills),
      list: new ExecuteListErasureDrills(executionContext, idGenerator, repos.erasureDrills),
    },
    erasures: {
      create: new ExecuteExecutePdErasure(executionContext, idGenerator, repos.erasures),
      get: new ExecuteGetErasureJob(executionContext, idGenerator, repos.erasures),
      list: new ExecuteListErasureJobs(executionContext, idGenerator, repos.erasures),
    },
  };
  return { repos, useCases: useCases as ErasuresDomainModule["useCases"] };
}
