/**
 * Routes for AntiPattern
 *
 * Generated by Routes Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: antipatterns
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type { FastifyInstance, FastifyRequest, FastifyReply } from "fastify";
import { getDependencyContainer } from "../../../infrastructure/dependency-container.js";
import { flagAntiPattern, getAntiPatternFlag, listAntiPatternFlags } from "../handlers/anti-pattern.handlers.js";
import { wrapHandlerInExecutionContext } from "../../../lib/execution-context-wrapper.js";

// Fastify types are available globally
export async function antiPatternRoutes(fastify: FastifyInstance) {
  // POST /v1/anti-patterns (unscoped; scope set for security middleware)
  fastify.post(
    "/v1/anti-patterns",
    { config: { scope: 'public' } },
    async (request: FastifyRequest<{ Params: Record<string, string>; Querystring: Record<string, string | string[] | undefined>; Body: unknown }>, reply: FastifyReply) => {
      await wrapHandlerInExecutionContext(request, async () => {
        const deps = getDependencyContainer().getAntipatternsDependenciesForRequest();
        await flagAntiPattern(request, reply, deps);
      });
    }
  );


  // GET /v1/anti-patterns (unscoped; scope set for security middleware)
  fastify.get(
    "/v1/anti-patterns",
    { config: { scope: 'public' } },
    async (request: FastifyRequest<{ Params: Record<string, string>; Querystring: Record<string, string | string[] | undefined>; Body: unknown }>, reply: FastifyReply) => {
      await wrapHandlerInExecutionContext(request, async () => {
        const deps = getDependencyContainer().getAntipatternsDependenciesForRequest();
        await listAntiPatternFlags(request, reply, deps);
      });
    }
  );


  // GET /v1/anti-patterns/{flagId} (unscoped; scope set for security middleware)
  fastify.get(
    "/v1/anti-patterns/:flagId",
    { config: { scope: 'public' } },
    async (request: FastifyRequest<{ Params: { flagId: string }; Querystring: Record<string, string | string[] | undefined>; Body: unknown }>, reply: FastifyReply) => {
      await wrapHandlerInExecutionContext(request, async () => {
        const deps = getDependencyContainer().getAntipatternsDependenciesForRequest();
        await getAntiPatternFlag(request, reply, deps);
      });
    }
  );


}
