/**
 * DynamoDB repository adapters barrel export
 *
 * Generated by Port Adapter Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: endorsement
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

export * from "./decision-repository.ddb.js";
export * from "./peer-repository.ddb.js";
export * from "./quarantine-repository.ddb.js";
export * from "./decision-repository.adapter.js";
export * from "./peer-repository.adapter.js";
export * from "./quarantine-repository.adapter.js";
