/**
 * ScanRepository - DynamoDB Implementation
 *
 * Generated by DynamoDB Repository Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: scans
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * ScanRepositoryDdb
 *
 * DDD: Infrastructure adapter for Scan repository.
 * ⚠️  Missing x-dynamodb metadata - implementation not generated.
 */

import type { ScanRepository } from "@offhash/services/scans";

export class ScanRepositoryDdb implements ScanRepository {
  constructor(private readonly dynamoClient: any) {}

  async scanTransactionProposal(input: Parameters<ScanRepository['scanTransactionProposal']>[0]): Promise<Awaited<ReturnType<ScanRepository['scanTransactionProposal']>>> {
    // TODO: Implement using x-dynamodb metadata
    throw new Error("Not implemented - missing x-dynamodb metadata");
  }

  async listPdScans(input: Parameters<ScanRepository['listPdScans']>[0]): Promise<Awaited<ReturnType<ScanRepository['listPdScans']>>> {
    // TODO: Implement using x-dynamodb metadata
    throw new Error("Not implemented - missing x-dynamodb metadata");
  }

  async getPdScanResult(input: Parameters<ScanRepository['getPdScanResult']>[0]): Promise<Awaited<ReturnType<ScanRepository['getPdScanResult']>>> {
    // TODO: Implement using x-dynamodb metadata
    throw new Error("Not implemented - missing x-dynamodb metadata");
  }
}
