/**
 * ScanRepositoryAdapter - Port Adapter Implementation
 *
 * Generated by Port Adapter Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: scans
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * ScanRepositoryAdapter
 *
 * DDD: Infrastructure adapter that implements ScanRepository port.
 * Handles infrastructure concerns (HTTP, database, external APIs).
 * Encapsulates Ddb creation - api-server passes dynamoClient only.
 */

import type {
  ScanRepository,
} from "@offhash/services/scans";
import type { AdapterDynamoDBClient } from "../_shared/dynamodb-client-types.js";
import { ScanRepositoryDdb } from "./scan-repository.ddb.js";

/**
 * ScanRepositoryAdapter
 *
 * Implements ScanRepository port for infrastructure layer.
 */
export class ScanRepositoryAdapter implements ScanRepository {
  private readonly ddb: ScanRepositoryDdb;

  constructor(
    private readonly dynamoClient: AdapterDynamoDBClient
  ) {
    this.ddb = new ScanRepositoryDdb(this.dynamoClient);
  }

  async scanTransactionProposal(input: Parameters<ScanRepository['scanTransactionProposal']>[0]): Promise<Awaited<ReturnType<ScanRepository['scanTransactionProposal']>>> {
    // Delegate to DynamoDB repository
    return await this.ddb.scanTransactionProposal(input);
  }

  async listPdScans(input: Parameters<ScanRepository['listPdScans']>[0]): Promise<Awaited<ReturnType<ScanRepository['listPdScans']>>> {
    // Delegate to DynamoDB repository
    return await this.ddb.listPdScans(input);
  }

  async getPdScanResult(input: Parameters<ScanRepository['getPdScanResult']>[0]): Promise<Awaited<ReturnType<ScanRepository['getPdScanResult']>>> {
    // Delegate to DynamoDB repository
    return await this.ddb.getPdScanResult(input);
  }
}
