/**
 * Hashes Zod Schemas - Runtime validation schemas
 *
 * Generated by Zod Schemas Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: hashes
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import { makeApi, Zodios, type ZodiosOptions } from '@zodios/core';
import { z } from 'zod';

const registerSaltedHash_Body = z
  .object({
    saltedHash: z.string().min(1),
    offChainStoreRef: z.string().min(1),
    pdRecordId: z.string().regex(/^pdr_[0-9A-HJKMNP-TV-Z]{26}$/),
    networkId: z
      .string()
      .regex(/^net_[0-9A-HJKMNP-TV-Z]{26}$/)
      .optional(),
    channelId: z.string().min(1).max(128).optional(),
  })
  .passthrough();

export const schemas: any = {
  registerSaltedHash_Body,
};

const endpoints = makeApi([
  {
    method: 'get',
    path: '/v1/hash-records',
    alias: 'listSaltedHashRecords',
    requestFormat: 'json',
    parameters: [
      {
        name: 'cursor',
        type: 'Query',
        schema: z.string().optional(),
      },
      {
        name: 'limit',
        type: 'Query',
        schema: z.number().int().gte(1).lte(200).optional().default(50),
      },
      {
        name: 'status',
        type: 'Query',
        schema: z.enum(['linked', 'orphaned']).optional(),
      },
      {
        name: 'networkId',
        type: 'Query',
        schema: z
          .string()
          .regex(/^net_[0-9A-HJKMNP-TV-Z]{26}$/)
          .optional(),
      },
      {
        name: 'channelId',
        type: 'Query',
        schema: z.string().min(1).max(128).optional(),
      },
    ],
    response: z
      .object({
        data: z
          .object({
            items: z.array(
              z
                .object({
                  hashId: z.string().regex(/^hsh_[0-9A-HJKMNP-TV-Z]{26}$/),
                  saltedHash: z.string(),
                  offChainStoreRef: z.string(),
                  pdRecordId: z.string().regex(/^pdr_[0-9A-HJKMNP-TV-Z]{26}$/),
                  status: z.enum(['linked', 'orphaned']),
                  networkId: z
                    .string()
                    .regex(/^net_[0-9A-HJKMNP-TV-Z]{26}$/)
                    .optional(),
                  channelId: z.string().min(1).max(128).optional(),
                  createdAt: z.string().datetime({ offset: true }),
                  orphanedAt: z.string().datetime({ offset: true }).optional(),
                })
                .passthrough()
            ),
            nextCursor: z.string().optional(),
          })
          .passthrough(),
        meta: z
          .object({
            requestId: z.string().uuid(),
            correlationId: z.string(),
            generatedAt: z.string().datetime({ offset: true }),
          })
          .partial()
          .passthrough()
          .optional(),
      })
      .passthrough(),
    errors: [
      {
        status: 401,
        description: `Missing or invalid API key`,
        schema: z
          .object({
            type: z.string().url(),
            title: z.string(),
            status: z.number().int(),
            detail: z.string(),
            instance: z.string().url(),
            code: z.string(),
          })
          .partial()
          .passthrough(),
      },
    ],
  },
  {
    method: 'post',
    path: '/v1/hash-records',
    alias: 'registerSaltedHash',
    requestFormat: 'json',
    parameters: [
      {
        name: 'body',
        type: 'Body',
        schema: registerSaltedHash_Body,
      },
      {
        name: 'Idempotency-Key',
        type: 'Header',
        schema: z.string().min(1).max(128),
      },
    ],
    response: z
      .object({
        data: z
          .object({
            hashId: z.string().regex(/^hsh_[0-9A-HJKMNP-TV-Z]{26}$/),
            saltedHash: z.string(),
            offChainStoreRef: z.string(),
            pdRecordId: z.string().regex(/^pdr_[0-9A-HJKMNP-TV-Z]{26}$/),
            status: z.enum(['linked', 'orphaned']),
            networkId: z
              .string()
              .regex(/^net_[0-9A-HJKMNP-TV-Z]{26}$/)
              .optional(),
            channelId: z.string().min(1).max(128).optional(),
            createdAt: z.string().datetime({ offset: true }),
            orphanedAt: z.string().datetime({ offset: true }).optional(),
          })
          .passthrough(),
        meta: z
          .object({
            requestId: z.string().uuid(),
            correlationId: z.string(),
            generatedAt: z.string().datetime({ offset: true }),
          })
          .partial()
          .passthrough()
          .optional(),
      })
      .passthrough(),
    errors: [
      {
        status: 400,
        description: `Malformed request`,
        schema: z
          .object({
            type: z.string().url(),
            title: z.string(),
            status: z.number().int(),
            detail: z.string(),
            instance: z.string().url(),
            code: z.string(),
          })
          .partial()
          .passthrough(),
      },
      {
        status: 401,
        description: `Missing or invalid API key`,
        schema: z
          .object({
            type: z.string().url(),
            title: z.string(),
            status: z.number().int(),
            detail: z.string(),
            instance: z.string().url(),
            code: z.string(),
          })
          .partial()
          .passthrough(),
      },
      {
        status: 409,
        description: `Idempotency key reuse with different body, or state conflict`,
        schema: z
          .object({
            type: z.string().url(),
            title: z.string(),
            status: z.number().int(),
            detail: z.string(),
            instance: z.string().url(),
            code: z.string(),
          })
          .partial()
          .passthrough(),
      },
    ],
  },
  {
    method: 'get',
    path: '/v1/hash-records/:hashId',
    alias: 'getSaltedHashRecord',
    requestFormat: 'json',
    parameters: [
      {
        name: 'hashId',
        type: 'Path',
        schema: z.string().regex(/^hsh_[0-9A-HJKMNP-TV-Z]{26}$/),
      },
    ],
    response: z
      .object({
        data: z
          .object({
            hashId: z.string().regex(/^hsh_[0-9A-HJKMNP-TV-Z]{26}$/),
            saltedHash: z.string(),
            offChainStoreRef: z.string(),
            pdRecordId: z.string().regex(/^pdr_[0-9A-HJKMNP-TV-Z]{26}$/),
            status: z.enum(['linked', 'orphaned']),
            networkId: z
              .string()
              .regex(/^net_[0-9A-HJKMNP-TV-Z]{26}$/)
              .optional(),
            channelId: z.string().min(1).max(128).optional(),
            createdAt: z.string().datetime({ offset: true }),
            orphanedAt: z.string().datetime({ offset: true }).optional(),
          })
          .passthrough(),
        meta: z
          .object({
            requestId: z.string().uuid(),
            correlationId: z.string(),
            generatedAt: z.string().datetime({ offset: true }),
          })
          .partial()
          .passthrough()
          .optional(),
      })
      .passthrough(),
    errors: [
      {
        status: 401,
        description: `Missing or invalid API key`,
        schema: z
          .object({
            type: z.string().url(),
            title: z.string(),
            status: z.number().int(),
            detail: z.string(),
            instance: z.string().url(),
            code: z.string(),
          })
          .partial()
          .passthrough(),
      },
      {
        status: 404,
        description: `Resource not found`,
        schema: z
          .object({
            type: z.string().url(),
            title: z.string(),
            status: z.number().int(),
            detail: z.string(),
            instance: z.string().url(),
            code: z.string(),
          })
          .partial()
          .passthrough(),
      },
    ],
  },
]);

export const api: any = new Zodios(
  'https://api.ddd-codegen-starter.local',
  endpoints
);

export function createApiClient(baseUrl: string, options?: ZodiosOptions): any {
  return new Zodios(baseUrl, endpoints, options);
}
