/**
 * GetErasure DTO Factory
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: erasures
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


import type { GetErasureJobParams } from "@offhash/core/erasures";

export function createGetErasureRequest(overrides: Partial<GetErasureJobParams> = {}) {
  const raw = {
    ...overrides,
  };

  return raw;
}
