/**
 * Policies Zod Schemas - Runtime validation schemas
 *
 * Generated by Zod Schemas Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: policies
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import { makeApi, Zodios, type ZodiosOptions } from '@zodios/core';
import { z } from 'zod';

const createFabricPolicy_Body = z
  .object({
    networkId: z.string().regex(/^net_[0-9A-HJKMNP-TV-Z]{26}$/),
    channelId: z.string().min(1).max(128),
    fabricVersion: z.string(),
    failClosed: z.boolean().optional().default(true),
    saltRequired: z.boolean().optional().default(true),
    allowPdcWithBlockToLive: z.boolean().optional().default(false),
    fab5097PdcMode: z.enum(['off', 'preview', 'on']).optional(),
    fieldCoverage: z
      .object({
        proposalPayload: z.boolean(),
        clientCertificate: z.boolean(),
        stateKeys: z.boolean(),
        stateValues: z.boolean(),
        events: z.boolean(),
        chaincodeResponse: z.boolean(),
        readSets: z.boolean(),
      })
      .partial()
      .passthrough()
      .optional(),
  })
  .passthrough();
const updateFabricPolicy_Body = z
  .object({
    fabricVersion: z.string(),
    failClosed: z.boolean(),
    saltRequired: z.boolean(),
    allowPdcWithBlockToLive: z.boolean(),
    fab5097PdcMode: z.enum(['off', 'preview', 'on']),
    fieldCoverage: z
      .object({
        proposalPayload: z.boolean(),
        clientCertificate: z.boolean(),
        stateKeys: z.boolean(),
        stateValues: z.boolean(),
        events: z.boolean(),
        chaincodeResponse: z.boolean(),
        readSets: z.boolean(),
      })
      .partial()
      .passthrough(),
    status: z.enum(['draft', 'published', 'archived']),
  })
  .partial()
  .passthrough();
const simulateFabricPolicy_Body = z
  .object({
    proposalRef: z.string().min(1).max(256),
    fields: z
      .object({
        proposalPayload: z.string(),
        clientCertificate: z.string(),
        stateKeys: z.array(z.string()),
        stateValues: z.array(z.string()),
        events: z.array(z.string()),
        chaincodeResponse: z.string(),
        readSets: z.array(z.string()),
      })
      .partial()
      .passthrough(),
  })
  .passthrough();

export const schemas: any = {
  createFabricPolicy_Body,
  updateFabricPolicy_Body,
  simulateFabricPolicy_Body,
};

const endpoints = makeApi([
  {
    method: 'get',
    path: '/v1/policies',
    alias: 'listFabricPolicies',
    requestFormat: 'json',
    parameters: [
      {
        name: 'cursor',
        type: 'Query',
        schema: z.string().optional(),
      },
      {
        name: 'limit',
        type: 'Query',
        schema: z.number().int().gte(1).lte(200).optional().default(50),
      },
      {
        name: 'networkId',
        type: 'Query',
        schema: z
          .string()
          .regex(/^net_[0-9A-HJKMNP-TV-Z]{26}$/)
          .optional(),
      },
      {
        name: 'status',
        type: 'Query',
        schema: z.enum(['draft', 'published', 'archived']).optional(),
      },
    ],
    response: z
      .object({
        data: z
          .object({
            items: z.array(
              z
                .object({
                  policyId: z.string().regex(/^pol_[0-9A-HJKMNP-TV-Z]{26}$/),
                  networkId: z.string().regex(/^net_[0-9A-HJKMNP-TV-Z]{26}$/),
                  channelId: z.string().min(1).max(128),
                  fabricVersion: z.string(),
                  failClosed: z.boolean(),
                  saltRequired: z.boolean().default(true),
                  allowPdcWithBlockToLive: z.boolean().optional(),
                  fab5097PdcMode: z.enum(['off', 'preview', 'on']).optional(),
                  fieldCoverage: z
                    .object({
                      proposalPayload: z.boolean(),
                      clientCertificate: z.boolean(),
                      stateKeys: z.boolean(),
                      stateValues: z.boolean(),
                      events: z.boolean(),
                      chaincodeResponse: z.boolean(),
                      readSets: z.boolean(),
                    })
                    .partial()
                    .passthrough()
                    .optional(),
                  status: z.enum(['draft', 'published', 'archived']),
                  createdAt: z.string().datetime({ offset: true }),
                  updatedAt: z.string().datetime({ offset: true }).optional(),
                })
                .passthrough()
            ),
            nextCursor: z.string().optional(),
          })
          .passthrough(),
        meta: z
          .object({
            requestId: z.string().uuid(),
            correlationId: z.string(),
            generatedAt: z.string().datetime({ offset: true }),
          })
          .partial()
          .passthrough()
          .optional(),
      })
      .passthrough(),
    errors: [
      {
        status: 401,
        description: `Missing or invalid API key`,
        schema: z
          .object({
            type: z.string().url(),
            title: z.string(),
            status: z.number().int(),
            detail: z.string(),
            instance: z.string().url(),
            code: z.string(),
          })
          .partial()
          .passthrough(),
      },
    ],
  },
  {
    method: 'post',
    path: '/v1/policies',
    alias: 'createFabricPolicy',
    requestFormat: 'json',
    parameters: [
      {
        name: 'body',
        type: 'Body',
        schema: createFabricPolicy_Body,
      },
      {
        name: 'Idempotency-Key',
        type: 'Header',
        schema: z.string().min(1).max(128),
      },
    ],
    response: z
      .object({
        data: z
          .object({
            policyId: z.string().regex(/^pol_[0-9A-HJKMNP-TV-Z]{26}$/),
            networkId: z.string().regex(/^net_[0-9A-HJKMNP-TV-Z]{26}$/),
            channelId: z.string().min(1).max(128),
            fabricVersion: z.string(),
            failClosed: z.boolean(),
            saltRequired: z.boolean().default(true),
            allowPdcWithBlockToLive: z.boolean().optional(),
            fab5097PdcMode: z.enum(['off', 'preview', 'on']).optional(),
            fieldCoverage: z
              .object({
                proposalPayload: z.boolean(),
                clientCertificate: z.boolean(),
                stateKeys: z.boolean(),
                stateValues: z.boolean(),
                events: z.boolean(),
                chaincodeResponse: z.boolean(),
                readSets: z.boolean(),
              })
              .partial()
              .passthrough()
              .optional(),
            status: z.enum(['draft', 'published', 'archived']),
            createdAt: z.string().datetime({ offset: true }),
            updatedAt: z.string().datetime({ offset: true }).optional(),
          })
          .passthrough(),
        meta: z
          .object({
            requestId: z.string().uuid(),
            correlationId: z.string(),
            generatedAt: z.string().datetime({ offset: true }),
          })
          .partial()
          .passthrough()
          .optional(),
      })
      .passthrough(),
    errors: [
      {
        status: 400,
        description: `Malformed request`,
        schema: z
          .object({
            type: z.string().url(),
            title: z.string(),
            status: z.number().int(),
            detail: z.string(),
            instance: z.string().url(),
            code: z.string(),
          })
          .partial()
          .passthrough(),
      },
      {
        status: 401,
        description: `Missing or invalid API key`,
        schema: z
          .object({
            type: z.string().url(),
            title: z.string(),
            status: z.number().int(),
            detail: z.string(),
            instance: z.string().url(),
            code: z.string(),
          })
          .partial()
          .passthrough(),
      },
      {
        status: 409,
        description: `Idempotency key reuse with different body, or state conflict`,
        schema: z
          .object({
            type: z.string().url(),
            title: z.string(),
            status: z.number().int(),
            detail: z.string(),
            instance: z.string().url(),
            code: z.string(),
          })
          .partial()
          .passthrough(),
      },
    ],
  },
  {
    method: 'get',
    path: '/v1/policies/:policyId',
    alias: 'getFabricPolicy',
    requestFormat: 'json',
    parameters: [
      {
        name: 'policyId',
        type: 'Path',
        schema: z.string().regex(/^pol_[0-9A-HJKMNP-TV-Z]{26}$/),
      },
    ],
    response: z
      .object({
        data: z
          .object({
            policyId: z.string().regex(/^pol_[0-9A-HJKMNP-TV-Z]{26}$/),
            networkId: z.string().regex(/^net_[0-9A-HJKMNP-TV-Z]{26}$/),
            channelId: z.string().min(1).max(128),
            fabricVersion: z.string(),
            failClosed: z.boolean(),
            saltRequired: z.boolean().default(true),
            allowPdcWithBlockToLive: z.boolean().optional(),
            fab5097PdcMode: z.enum(['off', 'preview', 'on']).optional(),
            fieldCoverage: z
              .object({
                proposalPayload: z.boolean(),
                clientCertificate: z.boolean(),
                stateKeys: z.boolean(),
                stateValues: z.boolean(),
                events: z.boolean(),
                chaincodeResponse: z.boolean(),
                readSets: z.boolean(),
              })
              .partial()
              .passthrough()
              .optional(),
            status: z.enum(['draft', 'published', 'archived']),
            createdAt: z.string().datetime({ offset: true }),
            updatedAt: z.string().datetime({ offset: true }).optional(),
          })
          .passthrough(),
        meta: z
          .object({
            requestId: z.string().uuid(),
            correlationId: z.string(),
            generatedAt: z.string().datetime({ offset: true }),
          })
          .partial()
          .passthrough()
          .optional(),
      })
      .passthrough(),
    errors: [
      {
        status: 401,
        description: `Missing or invalid API key`,
        schema: z
          .object({
            type: z.string().url(),
            title: z.string(),
            status: z.number().int(),
            detail: z.string(),
            instance: z.string().url(),
            code: z.string(),
          })
          .partial()
          .passthrough(),
      },
      {
        status: 404,
        description: `Resource not found`,
        schema: z
          .object({
            type: z.string().url(),
            title: z.string(),
            status: z.number().int(),
            detail: z.string(),
            instance: z.string().url(),
            code: z.string(),
          })
          .partial()
          .passthrough(),
      },
    ],
  },
  {
    method: 'patch',
    path: '/v1/policies/:policyId',
    alias: 'updateFabricPolicy',
    requestFormat: 'json',
    parameters: [
      {
        name: 'body',
        type: 'Body',
        schema: updateFabricPolicy_Body,
      },
      {
        name: 'policyId',
        type: 'Path',
        schema: z.string().regex(/^pol_[0-9A-HJKMNP-TV-Z]{26}$/),
      },
    ],
    response: z
      .object({
        data: z
          .object({
            policyId: z.string().regex(/^pol_[0-9A-HJKMNP-TV-Z]{26}$/),
            networkId: z.string().regex(/^net_[0-9A-HJKMNP-TV-Z]{26}$/),
            channelId: z.string().min(1).max(128),
            fabricVersion: z.string(),
            failClosed: z.boolean(),
            saltRequired: z.boolean().default(true),
            allowPdcWithBlockToLive: z.boolean().optional(),
            fab5097PdcMode: z.enum(['off', 'preview', 'on']).optional(),
            fieldCoverage: z
              .object({
                proposalPayload: z.boolean(),
                clientCertificate: z.boolean(),
                stateKeys: z.boolean(),
                stateValues: z.boolean(),
                events: z.boolean(),
                chaincodeResponse: z.boolean(),
                readSets: z.boolean(),
              })
              .partial()
              .passthrough()
              .optional(),
            status: z.enum(['draft', 'published', 'archived']),
            createdAt: z.string().datetime({ offset: true }),
            updatedAt: z.string().datetime({ offset: true }).optional(),
          })
          .passthrough(),
        meta: z
          .object({
            requestId: z.string().uuid(),
            correlationId: z.string(),
            generatedAt: z.string().datetime({ offset: true }),
          })
          .partial()
          .passthrough()
          .optional(),
      })
      .passthrough(),
    errors: [
      {
        status: 400,
        description: `Malformed request`,
        schema: z
          .object({
            type: z.string().url(),
            title: z.string(),
            status: z.number().int(),
            detail: z.string(),
            instance: z.string().url(),
            code: z.string(),
          })
          .partial()
          .passthrough(),
      },
      {
        status: 401,
        description: `Missing or invalid API key`,
        schema: z
          .object({
            type: z.string().url(),
            title: z.string(),
            status: z.number().int(),
            detail: z.string(),
            instance: z.string().url(),
            code: z.string(),
          })
          .partial()
          .passthrough(),
      },
      {
        status: 404,
        description: `Resource not found`,
        schema: z
          .object({
            type: z.string().url(),
            title: z.string(),
            status: z.number().int(),
            detail: z.string(),
            instance: z.string().url(),
            code: z.string(),
          })
          .partial()
          .passthrough(),
      },
      {
        status: 409,
        description: `Idempotency key reuse with different body, or state conflict`,
        schema: z
          .object({
            type: z.string().url(),
            title: z.string(),
            status: z.number().int(),
            detail: z.string(),
            instance: z.string().url(),
            code: z.string(),
          })
          .partial()
          .passthrough(),
      },
    ],
  },
  {
    method: 'post',
    path: '/v1/policies/:policyId/publish',
    alias: 'publishFabricPolicy',
    requestFormat: 'json',
    parameters: [
      {
        name: 'policyId',
        type: 'Path',
        schema: z.string().regex(/^pol_[0-9A-HJKMNP-TV-Z]{26}$/),
      },
      {
        name: 'Idempotency-Key',
        type: 'Header',
        schema: z.string().min(1).max(128),
      },
    ],
    response: z
      .object({
        data: z
          .object({
            policyId: z.string().regex(/^pol_[0-9A-HJKMNP-TV-Z]{26}$/),
            networkId: z.string().regex(/^net_[0-9A-HJKMNP-TV-Z]{26}$/),
            channelId: z.string().min(1).max(128),
            fabricVersion: z.string(),
            failClosed: z.boolean(),
            saltRequired: z.boolean().default(true),
            allowPdcWithBlockToLive: z.boolean().optional(),
            fab5097PdcMode: z.enum(['off', 'preview', 'on']).optional(),
            fieldCoverage: z
              .object({
                proposalPayload: z.boolean(),
                clientCertificate: z.boolean(),
                stateKeys: z.boolean(),
                stateValues: z.boolean(),
                events: z.boolean(),
                chaincodeResponse: z.boolean(),
                readSets: z.boolean(),
              })
              .partial()
              .passthrough()
              .optional(),
            status: z.enum(['draft', 'published', 'archived']),
            createdAt: z.string().datetime({ offset: true }),
            updatedAt: z.string().datetime({ offset: true }).optional(),
          })
          .passthrough(),
        meta: z
          .object({
            requestId: z.string().uuid(),
            correlationId: z.string(),
            generatedAt: z.string().datetime({ offset: true }),
          })
          .partial()
          .passthrough()
          .optional(),
      })
      .passthrough(),
    errors: [
      {
        status: 401,
        description: `Missing or invalid API key`,
        schema: z
          .object({
            type: z.string().url(),
            title: z.string(),
            status: z.number().int(),
            detail: z.string(),
            instance: z.string().url(),
            code: z.string(),
          })
          .partial()
          .passthrough(),
      },
      {
        status: 404,
        description: `Resource not found`,
        schema: z
          .object({
            type: z.string().url(),
            title: z.string(),
            status: z.number().int(),
            detail: z.string(),
            instance: z.string().url(),
            code: z.string(),
          })
          .partial()
          .passthrough(),
      },
      {
        status: 409,
        description: `Idempotency key reuse with different body, or state conflict`,
        schema: z
          .object({
            type: z.string().url(),
            title: z.string(),
            status: z.number().int(),
            detail: z.string(),
            instance: z.string().url(),
            code: z.string(),
          })
          .partial()
          .passthrough(),
      },
    ],
  },
  {
    method: 'post',
    path: '/v1/policies/:policyId/simulate',
    alias: 'simulateFabricPolicy',
    requestFormat: 'json',
    parameters: [
      {
        name: 'body',
        type: 'Body',
        schema: simulateFabricPolicy_Body,
      },
      {
        name: 'policyId',
        type: 'Path',
        schema: z.string().regex(/^pol_[0-9A-HJKMNP-TV-Z]{26}$/),
      },
      {
        name: 'Idempotency-Key',
        type: 'Header',
        schema: z.string().min(1).max(128),
      },
    ],
    response: z
      .object({
        data: z
          .object({
            proposalRef: z.string(),
            decision: z.enum(['allow', 'block', 'remediate']),
            endorsementAllowed: z.boolean(),
            pdHits: z
              .array(
                z
                  .object({
                    fieldPath: z.string(),
                    fabricSurface: z.enum([
                      'proposalPayload',
                      'clientCertificate',
                      'stateKeys',
                      'stateValues',
                      'events',
                      'chaincodeResponse',
                      'readSets',
                      'privateDataCollection',
                      'transientData',
                    ]),
                    hint: z.string().optional(),
                  })
                  .passthrough()
              )
              .optional(),
            remediationHints: z.array(z.string()).optional(),
          })
          .passthrough(),
        meta: z
          .object({
            requestId: z.string().uuid(),
            correlationId: z.string(),
            generatedAt: z.string().datetime({ offset: true }),
          })
          .partial()
          .passthrough()
          .optional(),
      })
      .passthrough(),
    errors: [
      {
        status: 400,
        description: `Malformed request`,
        schema: z
          .object({
            type: z.string().url(),
            title: z.string(),
            status: z.number().int(),
            detail: z.string(),
            instance: z.string().url(),
            code: z.string(),
          })
          .partial()
          .passthrough(),
      },
      {
        status: 401,
        description: `Missing or invalid API key`,
        schema: z
          .object({
            type: z.string().url(),
            title: z.string(),
            status: z.number().int(),
            detail: z.string(),
            instance: z.string().url(),
            code: z.string(),
          })
          .partial()
          .passthrough(),
      },
      {
        status: 404,
        description: `Resource not found`,
        schema: z
          .object({
            type: z.string().url(),
            title: z.string(),
            status: z.number().int(),
            detail: z.string(),
            instance: z.string().url(),
            code: z.string(),
          })
          .partial()
          .passthrough(),
      },
    ],
  },
]);

export const api: any = new Zodios(
  'https://api.ddd-codegen-starter.local',
  endpoints
);

export function createApiClient(baseUrl: string, options?: ZodiosOptions): any {
  return new Zodios(baseUrl, endpoints, options);
}
