/**
 * ErasureDrill Entity Factory
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: erasures
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


import type { ErasureDrillEntity } from "@offhash/core/erasures/models/index.js";
import { erasuresSchemas } from "@offhash/core/erasures";
import { ulid } from "ulid";

// Domain prefix from OpenAPI spec info.x-domain
const DOMAIN_PREFIX = "ers";

export function createErasureDrill(overrides: Partial<ErasureDrillEntity> = {}) {
  const raw = {
    id: overrides.id ?? `${DOMAIN_PREFIX}_${ulid().toLowerCase()}`,
    createdAt: overrides.createdAt ?? new Date().toISOString(),
    updatedAt: overrides.updatedAt ?? new Date().toISOString(),
    drillId: overrides.drillId ?? `drl_${ulid().toLowerCase()}`,
    networkId: overrides.networkId ?? `net_${ulid().toLowerCase()}`,
    result: overrides.result ?? "pass",
    ...overrides,
  };

  return erasuresSchemas.ErasureDrill.parse(raw);
}

export function erasureDrillBatch(n = 3, overrides = {}) {
  return Array.from({ length: n }, () => createErasureDrill(overrides));
}
