/**
 * GetSaltedHashRecord handler tests
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: hashes
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


import { describe, it, expect, beforeEach, vi } from "vitest";
import { getSaltedHashRecord } from "@offhash/api-server/domains/hashes/handlers";
import type { HashesDDDDependencies } from "@offhash/api-server/domains/hashes";
import { createMockRequest, createMockReply, createMockDependencies, TEST_ORG_ID } from "@offhash/tests/shared";
import { HASHES_USE_CASES } from "../__factories__/use-cases.js";

describe("GetSaltedHashRecord", () => {
  let mockRequest: ReturnType<typeof createMockRequest>;
  let mockReply: ReturnType<typeof createMockReply>;
  let mockDeps: HashesDDDDependencies;
  const orgId = TEST_ORG_ID;

  beforeEach(() => {
    mockRequest = createMockRequest({ orgId });
    mockReply = createMockReply();
    mockDeps = createMockDependencies<HashesDDDDependencies>(
      HASHES_USE_CASES,
      {
        // Mock use case dependencies here
      }
    );
  });

  it("should return 200 with entity when found", async () => {
    const entity = { id: 'mock-id', orgId } as any;
    const useCaseResult = { data: entity, meta: { correlationId: "test", timestamp: new Date().toISOString() } };
    
    vi.spyOn(mockDeps.executeGetSaltedHashRecord, "execute").mockResolvedValue(useCaseResult);
    mockRequest.params = { hashId: entity.id };

    await getSaltedHashRecord(mockRequest, mockReply, mockDeps);

    expect(mockDeps.executeGetSaltedHashRecord.execute).toHaveBeenCalledWith(expect.objectContaining({ hashId: entity.id }));
    expect(mockReply.code).toHaveBeenCalledWith(200);
    expect(mockReply.send).toHaveBeenCalledWith(useCaseResult);
  });

  it("should return error when entity not found", async () => {
    const nonExistentId = "non-existent-id";
    mockRequest.params = { hashId: nonExistentId };
    
    vi.spyOn(mockDeps.executeGetSaltedHashRecord, "execute").mockRejectedValue(
      new Error("Entity not found")
    );

    await expect(
      getSaltedHashRecord(mockRequest, mockReply, mockDeps)
    ).rejects.toThrow();
  });

});
