/**
 * Handler tests barrel export
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: hashes
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

export * from "./get-salted-hash-record.handler.test.js";
export * from "./list-salted-hash-records.handler.test.js";
export * from "./register-salted-hash.handler.test.js";
