/**
 * Handlers for HashRecord
 *
 * Generated by Handler Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: hashes
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type { FastifyRequest, FastifyReply } from "fastify";
import type { HashesDomainModule } from "../dependencies/hashes-ddd.dependencies.js";
import type { GetSaltedHashRecordInput, ListSaltedHashRecordsInput, RegisterSaltedHashInput } from "@offhash/services/hashes";
// Use cases are available via deps.useCases.<repoKey>.<verb>
// Execution context is automatically set up by route wrapper (wrapHandlerInExecutionContext)

/**
 * Handler for GET /v1/hash-records
 * Operation: listSaltedHashRecords
 */
export async function listSaltedHashRecords(
  request: FastifyRequest<{ Params: Record<string, string>; Querystring: { cursor?: string | string[], limit?: string | string[], status?: string | string[], networkId?: string | string[], channelId?: string | string[] }; Body: unknown }>,
  reply: FastifyReply,
  deps: HashesDomainModule
): Promise<void> {
  // Security: orgId validated by setOrgContext hook; use case gets it from execution context
  const input: ListSaltedHashRecordsInput = {
    ...(request.query ?? {}),
  };
  const result = await deps.useCases.hashRecords.list.execute(input);
  return reply.code(200).send(result);
}


/**
 * Handler for POST /v1/hash-records
 * Operation: registerSaltedHash
 */
export async function registerSaltedHash(
  request: FastifyRequest,
  reply: FastifyReply,
  deps: HashesDomainModule
): Promise<void> {
  // Security: orgId validated by setOrgContext hook; use case gets it from execution context
  const input: RegisterSaltedHashInput = {
    ...(request.body ?? {}),
  };
  const result = await deps.useCases.hashRecords.create.execute(input);
  return reply.code(201).send(result);
}


/**
 * Handler for GET /v1/hash-records/{hashId}
 * Operation: getSaltedHashRecord
 */
export async function getSaltedHashRecord(
  request: FastifyRequest<{ Params: { hashId: string }; Querystring: Record<string, string | string[] | undefined>; Body: unknown }>,
  reply: FastifyReply,
  deps: HashesDomainModule
): Promise<void> {
  // Security: orgId validated by setOrgContext hook; use case gets it from execution context
  const input: GetSaltedHashRecordInput = {
    hashId: request.params.hashId,
  };
  const result = await deps.useCases.hashRecords.get.execute(input);
  return reply.code(200).send(result);
}


