/**
 * Handlers for Complete
 *
 * Generated by Handler Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: configcerts
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type { FastifyRequest, FastifyReply } from "fastify";
import type { ConfigcertsDomainModule } from "../dependencies/configcerts-ddd.dependencies.js";
import type { CompleteConfigCertReviewInput } from "@offhash/services/configcerts";
// Use cases are available via deps.useCases.<repoKey>.<verb>
// Execution context is automatically set up by route wrapper (wrapHandlerInExecutionContext)

/**
 * Handler for POST /v1/config-cert-reviews/{reviewId}/complete
 * Operation: completeConfigCertReview
 */
export async function completeConfigCertReview(
  request: FastifyRequest<{ Params: { reviewId: string }; Querystring: Record<string, string | string[] | undefined>; Body: unknown }>,
  reply: FastifyReply,
  deps: ConfigcertsDomainModule
): Promise<void> {
  // Security: orgId validated by setOrgContext hook; use case gets it from execution context
  const input: CompleteConfigCertReviewInput = {
    reviewId: request.params.reviewId,
    ...(request.body ?? {}),
  };
  const result = await deps.useCases.completes.create.execute(input);
  return reply.code(200).send(result);
}


