/**
 * HashRecordRepository Port - Application port interface
 *
 * Generated by Port Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: hashes
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * HashRecordRepository Port
 *
 * DDD: Application port for hashrecordrepository operations.
 * This is an application-level abstraction, not a domain concept.
 * Implementations live in adapters layer.
 */

import type { GetSaltedHashRecordInput, GetSaltedHashRecordOutput, ListSaltedHashRecordsInput, ListSaltedHashRecordsOutput, RegisterSaltedHashInput, RegisterSaltedHashOutput } from "../dto/hash-record.dto";
export interface HashRecordRepository {
  listSaltedHashRecords(input: ListSaltedHashRecordsInput): Promise<ListSaltedHashRecordsOutput>;
  registerSaltedHash(input: RegisterSaltedHashInput): Promise<RegisterSaltedHashOutput>;
  getSaltedHashRecord(input: GetSaltedHashRecordInput): Promise<GetSaltedHashRecordOutput>;
}

export type { GetSaltedHashRecordInput, GetSaltedHashRecordOutput, ListSaltedHashRecordsInput, ListSaltedHashRecordsOutput, RegisterSaltedHashInput, RegisterSaltedHashOutput } from "../dto/hash-record.dto";
