/**
 * Policies DDD Dependencies - Composition root
 *
 * Generated by Dependencies Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: policies
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * Policies Domain Module - Composition root
 *
 * DDD: Composition root for policies domain. Exposes repos (ports) and use cases
 * grouped by aggregate. No orgId at build time — use execution context at call time.
 */

import {
  PolicyRepositoryAdapter,
  SimulateRepositoryAdapter,
} from "@offhash/adapters/policies";
import { getIdGeneratorService } from "@offhash/adapters";
import type { AdapterDynamoDBClient } from "@offhash/adapters";
import { executionContextService } from "../../../lib/execution-context.service.js";
// Use-case constructors (concrete)
import {
  ExecuteCreateFabricPolicy,
  ExecuteGetFabricPolicy,
  ExecuteListFabricPolicies,
  ExecutePublishFabricPolicy,
  ExecuteSimulateFabricPolicy,
  ExecuteUpdateFabricPolicy,
} from "@offhash/services/policies/usecases";
// Ports (interfaces)
import type {
  PolicyRepository,
  SimulateRepository,
} from "@offhash/services/policies/ports";

export interface PoliciesDomainModule {
  repos: {
    policies: PolicyRepository;
    simulates: SimulateRepository;
  };
  useCases: {
    policies: {
      create: ExecuteCreateFabricPolicy;
      get: ExecuteGetFabricPolicy;
      list: ExecuteListFabricPolicies;
      update: ExecuteUpdateFabricPolicy;
    };
    simulates: {
      get: ExecuteSimulateFabricPolicy;
    };
  };
}

export function buildPoliciesDomainModule(
  dynamoClient: AdapterDynamoDBClient,
): PoliciesDomainModule {
  // Adapters implementing ports (adapters encapsulate Ddb)
  const repos = (() => {
    const obj: {
      policies?: PolicyRepository;
      simulates?: SimulateRepository;
    } = {};

    obj.policies = new PolicyRepositoryAdapter(dynamoClient);
    obj.simulates = new SimulateRepositoryAdapter(dynamoClient);
    return {
      policies: obj.policies!,
      simulates: obj.simulates!,
    };
  })();

  const executionContext = executionContextService;
  const idGenerator = getIdGeneratorService();

  // Use cases depend only on ports (repos.*)
  const useCases = {
    policies: {
      create: new ExecuteCreateFabricPolicy(executionContext, idGenerator, repos.policies),
      get: new ExecuteGetFabricPolicy(executionContext, idGenerator, repos.policies),
      list: new ExecuteListFabricPolicies(executionContext, idGenerator, repos.policies),
      update: new ExecuteUpdateFabricPolicy(executionContext, idGenerator, repos.policies),
    },
    simulates: {
      get: new ExecuteSimulateFabricPolicy(executionContext, idGenerator, repos.simulates),
    },
  };
  return { repos, useCases: useCases as PoliciesDomainModule["useCases"] };
}
