/**
 * ListPeer DTO Factory
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: endorsement
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


import type { ListEndorsementPeersParams } from "@offhash/core/endorsement";

export function createListPeerRequest(overrides: Partial<ListEndorsementPeersParams> = {}) {
  const raw = {
    ...overrides,
  };

  return raw;
}
