/**
 * Peer DTOs - Application DTOs
 *
 * Generated by DTO Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: endorsement
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * Peer DTOs
 *
 * DDD: Application DTOs for Peer use cases.
 */

import type { GetEndorsementPeerParams, ListEndorsementPeersParams } from "@offhash/core/endorsement/types";

export type ListEndorsementPeersInput = ListEndorsementPeersParams;

export type GetEndorsementPeerInput = GetEndorsementPeerParams;

export type ListEndorsementPeersOutput = {};

export type GetEndorsementPeerOutput = {};
