/**
 * Quarantine DTOs - Application DTOs
 *
 * Generated by DTO Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: endorsement
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * Quarantine DTOs
 *
 * DDD: Application DTOs for Quarantine use cases.
 */

import type { QuarantineEndorsementPeerParams, QuarantineEndorsementPeerRequestInput } from "@offhash/core/endorsement/types";

export type QuarantineEndorsementPeerInput = QuarantineEndorsementPeerParams & QuarantineEndorsementPeerRequestInput;

export type QuarantineEndorsementPeerOutput = {};
