/**
 * HashRecord DTOs - Application DTOs
 *
 * Generated by DTO Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: hashes
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * HashRecord DTOs
 *
 * DDD: Application DTOs for HashRecord use cases.
 */

import type { GetSaltedHashRecordParams, ListSaltedHashRecordsParams, RegisterSaltedHashRequestInput } from "@offhash/core/hashes/types";

export type ListSaltedHashRecordsInput = ListSaltedHashRecordsParams;

export type RegisterSaltedHashInput = RegisterSaltedHashRequestInput;

export type GetSaltedHashRecordInput = GetSaltedHashRecordParams;

export type ListSaltedHashRecordsOutput = {};

export type RegisterSaltedHashOutput = {};

export type GetSaltedHashRecordOutput = {};
