/**
 * CreateConfigCertReview handler tests
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: configcerts
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


import { describe, it, expect, beforeEach, vi } from "vitest";
import { createConfigCertReview } from "@offhash/api-server/domains/configcerts/handlers";
import type { ConfigcertsDDDDependencies } from "@offhash/api-server/domains/configcerts";
import { createConfigCertReview as createConfigCertReviewEntity } from "@offhash/factories/configcerts";
import { createMockRequest, createMockReply, createMockDependencies, TEST_ORG_ID } from "@offhash/tests/shared";
import { CONFIGCERTS_USE_CASES } from "../__factories__/use-cases.js";

describe("CreateConfigCertReview", () => {
  let mockRequest: ReturnType<typeof createMockRequest>;
  let mockReply: ReturnType<typeof createMockReply>;
  let mockDeps: ConfigcertsDDDDependencies;
  const orgId = TEST_ORG_ID;

  beforeEach(() => {
    mockRequest = createMockRequest({ orgId });
    mockReply = createMockReply();
    mockDeps = createMockDependencies<ConfigcertsDDDDependencies>(
      CONFIGCERTS_USE_CASES,
      {
        // Mock use case dependencies here
      }
    );
  });

  it("should return 201 with created entity", async () => {
    const input = {} as any;
    const entity = createConfigCertReviewEntity({ orgId });
    const useCaseResult = { data: entity, meta: { correlationId: "test", timestamp: new Date().toISOString() } };
    
    mockRequest.body = input;
    vi.spyOn(mockDeps.executeCreateConfigCertReview, "execute").mockResolvedValue(useCaseResult);

    await createConfigCertReview(mockRequest, mockReply, mockDeps);

    expect(mockDeps.executeCreateConfigCertReview.execute).toHaveBeenCalledWith(expect.anything());
    expect(mockReply.code).toHaveBeenCalledWith(201);
    expect(mockReply.send).toHaveBeenCalledWith(useCaseResult);
  });

});
