/**
 * GetConfigCertReview handler tests
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: configcerts
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


import { describe, it, expect, beforeEach, vi } from "vitest";
import { getConfigCertReview } from "@offhash/api-server/domains/configcerts/handlers";
import type { ConfigcertsDDDDependencies } from "@offhash/api-server/domains/configcerts";
import { createConfigCertReview as createConfigCertReviewEntity } from "@offhash/factories/configcerts";
import { createMockRequest, createMockReply, createMockDependencies, TEST_ORG_ID } from "@offhash/tests/shared";
import { CONFIGCERTS_USE_CASES } from "../__factories__/use-cases.js";

describe("GetConfigCertReview", () => {
  let mockRequest: ReturnType<typeof createMockRequest>;
  let mockReply: ReturnType<typeof createMockReply>;
  let mockDeps: ConfigcertsDDDDependencies;
  const orgId = TEST_ORG_ID;

  beforeEach(() => {
    mockRequest = createMockRequest({ orgId });
    mockReply = createMockReply();
    mockDeps = createMockDependencies<ConfigcertsDDDDependencies>(
      CONFIGCERTS_USE_CASES,
      {
        // Mock use case dependencies here
      }
    );
  });

  it("should return 200 with entity when found", async () => {
    const entity = createConfigCertReviewEntity({ orgId });
    const useCaseResult = { data: entity, meta: { correlationId: "test", timestamp: new Date().toISOString() } };
    
    vi.spyOn(mockDeps.executeGetConfigCertReview, "execute").mockResolvedValue(useCaseResult);
    mockRequest.params = { reviewId: entity.id };

    await getConfigCertReview(mockRequest, mockReply, mockDeps);

    expect(mockDeps.executeGetConfigCertReview.execute).toHaveBeenCalledWith(expect.objectContaining({ reviewId: entity.id }));
    expect(mockReply.code).toHaveBeenCalledWith(200);
    expect(mockReply.send).toHaveBeenCalledWith(useCaseResult);
  });

  it("should return error when entity not found", async () => {
    const nonExistentId = "non-existent-id";
    mockRequest.params = { reviewId: nonExistentId };
    
    vi.spyOn(mockDeps.executeGetConfigCertReview, "execute").mockRejectedValue(
      new Error("Entity not found")
    );

    await expect(
      getConfigCertReview(mockRequest, mockReply, mockDeps)
    ).rejects.toThrow();
  });

});
