/**
 * ConfigCertReview Entity - Domain model
 *
 * Generated by Entity Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: configcerts
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type { components } from "../openapi/configcerts.openapi.types.js";
import { schemas } from "../schemas/configcerts.schemas.js";

/**
 * Entity: ConfigCertReviewEntity
 * Description: Represents the ConfigCertReview domain model.
 * Source: schemas.ConfigCertReview
 * Type: Persisted Entity (x-dynamodb)
 */
export const ConfigCertReviewEntitySchema = schemas.ConfigCertReview;
export type ConfigCertReviewEntity = components["schemas"]["ConfigCertReview"];
