/**
 * Handlers for Decision
 *
 * Generated by Handler Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: endorsement
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type { FastifyRequest, FastifyReply } from "fastify";
import type { EndorsementDomainModule } from "../dependencies/endorsement-ddd.dependencies.js";
import type { ListEndorsementDecisionsInput } from "@offhash/services/endorsement";
// Use cases are available via deps.useCases.<repoKey>.<verb>
// Execution context is automatically set up by route wrapper (wrapHandlerInExecutionContext)

/**
 * Handler for GET /v1/endorsement/decisions
 * Operation: listEndorsementDecisions
 */
export async function listEndorsementDecisions(
  request: FastifyRequest<{ Params: Record<string, string>; Querystring: { cursor?: string | string[], limit?: string | string[], decision?: string | string[] }; Body: unknown }>,
  reply: FastifyReply,
  deps: EndorsementDomainModule
): Promise<void> {
  // Security: orgId validated by setOrgContext hook; use case gets it from execution context
  const input: ListEndorsementDecisionsInput = {
    ...(request.query ?? {}),
  };
  const result = await deps.useCases.decisions.list.execute(input);
  return reply.code(200).send(result);
}


