/**
 * Handlers for Peer
 *
 * Generated by Handler Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: endorsement
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type { FastifyRequest, FastifyReply } from "fastify";
import type { EndorsementDomainModule } from "../dependencies/endorsement-ddd.dependencies.js";
import type { GetEndorsementPeerInput, ListEndorsementPeersInput } from "@offhash/services/endorsement";
// Use cases are available via deps.useCases.<repoKey>.<verb>
// Execution context is automatically set up by route wrapper (wrapHandlerInExecutionContext)

/**
 * Handler for GET /v1/endorsement/peers
 * Operation: listEndorsementPeers
 */
export async function listEndorsementPeers(
  request: FastifyRequest<{ Params: Record<string, string>; Querystring: { cursor?: string | string[], limit?: string | string[], status?: string | string[], orgId?: string | string[] }; Body: unknown }>,
  reply: FastifyReply,
  deps: EndorsementDomainModule
): Promise<void> {
  // Security: orgId validated by setOrgContext hook; use case gets it from execution context
  const input: ListEndorsementPeersInput = {
    ...(request.query ?? {}),
  };
  const result = await deps.useCases.peers.list.execute(input);
  return reply.code(200).send(result);
}


/**
 * Handler for GET /v1/endorsement/peers/{peerId}
 * Operation: getEndorsementPeer
 */
export async function getEndorsementPeer(
  request: FastifyRequest<{ Params: { peerId: string }; Querystring: Record<string, string | string[] | undefined>; Body: unknown }>,
  reply: FastifyReply,
  deps: EndorsementDomainModule
): Promise<void> {
  // Security: orgId validated by setOrgContext hook; use case gets it from execution context
  const input: GetEndorsementPeerInput = {
    peerId: request.params.peerId,
  };
  const result = await deps.useCases.peers.get.execute(input);
  return reply.code(200).send(result);
}


