/**
 * Handlers for Quarantine
 *
 * Generated by Handler Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: endorsement
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type { FastifyRequest, FastifyReply } from "fastify";
import type { EndorsementDomainModule } from "../dependencies/endorsement-ddd.dependencies.js";
import type { QuarantineEndorsementPeerInput } from "@offhash/services/endorsement";
// Use cases are available via deps.useCases.<repoKey>.<verb>
// Execution context is automatically set up by route wrapper (wrapHandlerInExecutionContext)

/**
 * Handler for POST /v1/endorsement/peers/{peerId}/quarantine
 * Operation: quarantineEndorsementPeer
 */
export async function quarantineEndorsementPeer(
  request: FastifyRequest<{ Params: { peerId: string }; Querystring: Record<string, string | string[] | undefined>; Body: unknown }>,
  reply: FastifyReply,
  deps: EndorsementDomainModule
): Promise<void> {
  // Security: orgId validated by setOrgContext hook; use case gets it from execution context
  const input: QuarantineEndorsementPeerInput = {
    peerId: request.params.peerId,
    ...(request.body ?? {}),
  };
  const result = await deps.useCases.quarantines.get.execute(input);
  return reply.code(200).send(result);
}


