/**
 * Routes for Complete
 *
 * Generated by Routes Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: configcerts
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type { FastifyInstance, FastifyRequest, FastifyReply } from "fastify";
import { getDependencyContainer } from "../../../infrastructure/dependency-container.js";
import { completeConfigCertReview } from "../handlers/complete.handlers.js";
import { wrapHandlerInExecutionContext } from "../../../lib/execution-context-wrapper.js";

// Fastify types are available globally
export async function completeRoutes(fastify: FastifyInstance) {
  // POST /v1/config-cert-reviews/{reviewId}/complete (unscoped; scope set for security middleware)
  fastify.post(
    "/v1/config-cert-reviews/:reviewId/complete",
    { config: { scope: 'public' } },
    async (request: FastifyRequest<{ Params: { reviewId: string }; Querystring: Record<string, string | string[] | undefined>; Body: unknown }>, reply: FastifyReply) => {
      await wrapHandlerInExecutionContext(request, async () => {
        const deps = getDependencyContainer().getConfigcertsDependenciesForRequest();
        await completeConfigCertReview(request, reply, deps);
      });
    }
  );


}
