/**
 * Routes for ConfigCertReview
 *
 * Generated by Routes Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: configcerts
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type { FastifyInstance, FastifyRequest, FastifyReply } from "fastify";
import { getDependencyContainer } from "../../../infrastructure/dependency-container.js";
import { createConfigCertReview, getConfigCertReview, listConfigCertReviews } from "../handlers/config-cert-review.handlers.js";
import { wrapHandlerInExecutionContext } from "../../../lib/execution-context-wrapper.js";

// Fastify types are available globally
export async function configCertReviewRoutes(fastify: FastifyInstance) {
  // POST /v1/config-cert-reviews (unscoped; scope set for security middleware)
  fastify.post(
    "/v1/config-cert-reviews",
    { config: { scope: 'public' } },
    async (request: FastifyRequest<{ Params: Record<string, string>; Querystring: Record<string, string | string[] | undefined>; Body: unknown }>, reply: FastifyReply) => {
      await wrapHandlerInExecutionContext(request, async () => {
        const deps = getDependencyContainer().getConfigcertsDependenciesForRequest();
        await createConfigCertReview(request, reply, deps);
      });
    }
  );


  // GET /v1/config-cert-reviews (unscoped; scope set for security middleware)
  fastify.get(
    "/v1/config-cert-reviews",
    { config: { scope: 'public' } },
    async (request: FastifyRequest<{ Params: Record<string, string>; Querystring: Record<string, string | string[] | undefined>; Body: unknown }>, reply: FastifyReply) => {
      await wrapHandlerInExecutionContext(request, async () => {
        const deps = getDependencyContainer().getConfigcertsDependenciesForRequest();
        await listConfigCertReviews(request, reply, deps);
      });
    }
  );


  // GET /v1/config-cert-reviews/{reviewId} (unscoped; scope set for security middleware)
  fastify.get(
    "/v1/config-cert-reviews/:reviewId",
    { config: { scope: 'public' } },
    async (request: FastifyRequest<{ Params: { reviewId: string }; Querystring: Record<string, string | string[] | undefined>; Body: unknown }>, reply: FastifyReply) => {
      await wrapHandlerInExecutionContext(request, async () => {
        const deps = getDependencyContainer().getConfigcertsDependenciesForRequest();
        await getConfigCertReview(request, reply, deps);
      });
    }
  );


}
