/**
 * ExecuteListErasureDrills - Application use case
 *
 * Generated by Use Case Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: erasures
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * ExecuteListErasureDrills Use Case
 *
 * DDD: Application use case for list ErasureDrill.
 * Orchestrates the business flow using ports (interfaces).
 */

import type { ListErasureDrillsInput, ListErasureDrillsOutput } from "../dto/erasure-drill.dto";
import type { ExecutionContextService, IdGeneratorService } from "@offhash/services/_shared/index.js";
import type { ErasureDrillRepository } from "../ports";

export class ExecuteListErasureDrills {
  constructor(
    private readonly context: ExecutionContextService,
    private readonly idGenerator: IdGeneratorService,
    private readonly erasureDrill: ErasureDrillRepository
  ) {}

  async execute(input: ListErasureDrillsInput): Promise<ListErasureDrillsOutput> {
    // Generate correlation ID for this request (domain-prefixed format: {domain_prefix}_{ulid})
    const correlationId = this.idGenerator.ersId();

    // All field names extracted from OpenAPI spec: none
    // List entities via repository
    const result = await this.erasureDrill.listErasureDrills({ ...input, orgId: this.context.getOrgId(), correlationId } as any);

    return result as ListErasureDrillsOutput;
  }
}
