/**
 * Domain routes – register all domain route modules.
 *
 * AUTO-GENERATED by codegen (api_server_domain_routes). Do not edit by hand.
 * Rescans platform/api-server/src/domains and includes only domains that have
 * routes/index.ts and dependencies/{domain}-ddd.dependencies.ts.
 * Extension excludes/imports from x-codegen.api-server.extensions in OpenAPI YAML.
 */

import type { FastifyInstance } from "fastify";
import { registerDomainFromModule } from "./route-registration.js";

// Static imports so the bundle includes all domain route modules
import * as antipatternsRoutes from "../../domains/antipatterns/routes/index.js";
import * as configcertsRoutes from "../../domains/configcerts/routes/index.js";
import * as endorsementRoutes from "../../domains/endorsement/routes/index.js";
import * as erasuresRoutes from "../../domains/erasures/routes/index.js";
import * as hashesRoutes from "../../domains/hashes/routes/index.js";
import * as identityRoutes from "../../domains/identity/routes/index.js";
import * as policiesRoutes from "../../domains/policies/routes/index.js";
import * as reportingRoutes from "../../domains/reporting/routes/index.js";
import * as scansRoutes from "../../domains/scans/routes/index.js";

const DOMAIN_MODULES: Array<{
  domain: string;
  mod: Record<string, unknown>;
  exclude?: string[];
}> = [
  { domain: "antipatterns", mod: antipatternsRoutes },
  { domain: "configcerts", mod: configcertsRoutes },
  { domain: "endorsement", mod: endorsementRoutes },
  { domain: "erasures", mod: erasuresRoutes },
  { domain: "hashes", mod: hashesRoutes },
  {
    domain: "identity", mod: identityRoutes,
    // Keep login/logout/refresh/me registered for console sessions; exclude unused stubs only.
    exclude: ["authRoutes", "signupRoutes", "sessionRoutes", "tokenRoutes", "profileRoutes"],
  },
  { domain: "policies", mod: policiesRoutes },
  { domain: "reporting", mod: reportingRoutes },
  { domain: "scans", mod: scansRoutes },
];

export async function registerAllDomainRoutes(
  fastify: FastifyInstance,
): Promise<void> {
  console.log("[DEBUG] Registering domain routes...");
  try {
    for (const { domain, mod, exclude } of DOMAIN_MODULES) {
      await registerDomainFromModule(fastify, domain, mod, exclude ?? []);
    }
    console.log("[DEBUG] ✅ All domain routes registered");
  } catch (error: unknown) {
    const err = error instanceof Error ? error : new Error(String(error));
    console.error("[DEBUG] ❌ Error registering domain routes:", err.message);
    if (err.stack) console.error(err.stack);
    throw error;
  }
}
