/**
 * Routes for HashRecord
 *
 * Generated by Routes Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: hashes
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type { FastifyInstance, FastifyRequest, FastifyReply } from "fastify";
import { getDependencyContainer } from "../../../infrastructure/dependency-container.js";
import { getSaltedHashRecord, listSaltedHashRecords, registerSaltedHash } from "../handlers/hash-record.handlers.js";
import { wrapHandlerInExecutionContext } from "../../../lib/execution-context-wrapper.js";

// Fastify types are available globally
export async function hashRecordRoutes(fastify: FastifyInstance) {
  // GET /v1/hash-records (unscoped; scope set for security middleware)
  fastify.get(
    "/v1/hash-records",
    { config: { scope: 'public' } },
    async (request: FastifyRequest<{ Params: Record<string, string>; Querystring: Record<string, string | string[] | undefined>; Body: unknown }>, reply: FastifyReply) => {
      await wrapHandlerInExecutionContext(request, async () => {
        const deps = getDependencyContainer().getHashesDependenciesForRequest();
        await listSaltedHashRecords(request, reply, deps);
      });
    }
  );


  // POST /v1/hash-records (unscoped; scope set for security middleware)
  fastify.post(
    "/v1/hash-records",
    { config: { scope: 'public' } },
    async (request: FastifyRequest<{ Params: Record<string, string>; Querystring: Record<string, string | string[] | undefined>; Body: unknown }>, reply: FastifyReply) => {
      await wrapHandlerInExecutionContext(request, async () => {
        const deps = getDependencyContainer().getHashesDependenciesForRequest();
        await registerSaltedHash(request, reply, deps);
      });
    }
  );


  // GET /v1/hash-records/{hashId} (unscoped; scope set for security middleware)
  fastify.get(
    "/v1/hash-records/:hashId",
    { config: { scope: 'public' } },
    async (request: FastifyRequest<{ Params: { hashId: string }; Querystring: Record<string, string | string[] | undefined>; Body: unknown }>, reply: FastifyReply) => {
      await wrapHandlerInExecutionContext(request, async () => {
        const deps = getDependencyContainer().getHashesDependenciesForRequest();
        await getSaltedHashRecord(request, reply, deps);
      });
    }
  );


}
