/**
 * DpiaExportRepositoryAdapter - Port Adapter Implementation
 *
 * Generated by Port Adapter Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: reporting
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * DpiaExportRepositoryAdapter
 *
 * DDD: Infrastructure adapter that implements DpiaExportRepository port.
 * Handles infrastructure concerns (HTTP, database, external APIs).
 * Encapsulates Ddb creation - api-server passes dynamoClient only.
 */

import type {
  DpiaExportRepository,
} from "@offhash/services/reporting";
import type { AdapterDynamoDBClient } from "../_shared/dynamodb-client-types.js";
import { DpiaExportRepositoryDdb } from "./dpia-export-repository.ddb.js";

/**
 * DpiaExportRepositoryAdapter
 *
 * Implements DpiaExportRepository port for infrastructure layer.
 */
export class DpiaExportRepositoryAdapter implements DpiaExportRepository {
  private readonly ddb: DpiaExportRepositoryDdb;

  constructor(
    private readonly dynamoClient: AdapterDynamoDBClient
  ) {
    this.ddb = new DpiaExportRepositoryDdb(this.dynamoClient);
  }

  async createDpiaExport(input: Parameters<DpiaExportRepository['createDpiaExport']>[0]): Promise<Awaited<ReturnType<DpiaExportRepository['createDpiaExport']>>> {
    // Delegate to DynamoDB repository
    return await this.ddb.createDpiaExport(input);
  }
}
