/**
 * Routes for ErasureDrill
 *
 * Generated by Routes Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: erasures
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type { FastifyInstance, FastifyRequest, FastifyReply } from "fastify";
import { getDependencyContainer } from "../../../infrastructure/dependency-container.js";
import { createErasureDrill, getErasureDrill, listErasureDrills } from "../handlers/erasure-drill.handlers.js";
import { wrapHandlerInExecutionContext } from "../../../lib/execution-context-wrapper.js";

// Fastify types are available globally
export async function erasureDrillRoutes(fastify: FastifyInstance) {
  // POST /v1/erasure-drills (unscoped; scope set for security middleware)
  fastify.post(
    "/v1/erasure-drills",
    { config: { scope: 'public' } },
    async (request: FastifyRequest<{ Params: Record<string, string>; Querystring: Record<string, string | string[] | undefined>; Body: unknown }>, reply: FastifyReply) => {
      await wrapHandlerInExecutionContext(request, async () => {
        const deps = getDependencyContainer().getErasuresDependenciesForRequest();
        await createErasureDrill(request, reply, deps);
      });
    }
  );


  // GET /v1/erasure-drills (unscoped; scope set for security middleware)
  fastify.get(
    "/v1/erasure-drills",
    { config: { scope: 'public' } },
    async (request: FastifyRequest<{ Params: Record<string, string>; Querystring: Record<string, string | string[] | undefined>; Body: unknown }>, reply: FastifyReply) => {
      await wrapHandlerInExecutionContext(request, async () => {
        const deps = getDependencyContainer().getErasuresDependenciesForRequest();
        await listErasureDrills(request, reply, deps);
      });
    }
  );


  // GET /v1/erasure-drills/{drillId} (unscoped; scope set for security middleware)
  fastify.get(
    "/v1/erasure-drills/:drillId",
    { config: { scope: 'public' } },
    async (request: FastifyRequest<{ Params: { drillId: string }; Querystring: Record<string, string | string[] | undefined>; Body: unknown }>, reply: FastifyReply) => {
      await wrapHandlerInExecutionContext(request, async () => {
        const deps = getDependencyContainer().getErasuresDependenciesForRequest();
        await getErasureDrill(request, reply, deps);
      });
    }
  );


}
