/**
 * Policy DTOs - Application DTOs
 *
 * Generated by DTO Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: policies
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * Policy DTOs
 *
 * DDD: Application DTOs for Policy use cases.
 */

import type { CreateFabricPolicyRequestInput, GetFabricPolicyParams, ListFabricPoliciesParams, UpdateFabricPolicyParams, UpdateFabricPolicyRequestInput } from "@offhash/core/policies/types";

export type ListFabricPoliciesInput = ListFabricPoliciesParams;

export type CreateFabricPolicyInput = CreateFabricPolicyRequestInput;

export type GetFabricPolicyInput = GetFabricPolicyParams;

export type UpdateFabricPolicyInput = UpdateFabricPolicyParams & UpdateFabricPolicyRequestInput;

export type ListFabricPoliciesOutput = {};

export type CreateFabricPolicyOutput = {};

export type GetFabricPolicyOutput = {};

export type UpdateFabricPolicyOutput = {};
