/**
 * Simulate DTOs - Application DTOs
 *
 * Generated by DTO Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: policies
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * Simulate DTOs
 *
 * DDD: Application DTOs for Simulate use cases.
 */

import type { SimulateFabricPolicyParams, SimulateFabricPolicyRequestInput } from "@offhash/core/policies/types";

export type SimulateFabricPolicyInput = SimulateFabricPolicyParams & SimulateFabricPolicyRequestInput;

export type SimulateFabricPolicyOutput = {};
