/**
 * ErasureDrill Entity - Domain model
 *
 * Generated by Entity Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: erasures
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type { components } from "../openapi/erasures.openapi.types.js";
import { schemas } from "../schemas/erasures.schemas.js";

/**
 * Entity: ErasureDrillEntity
 * Description: Represents the ErasureDrill domain model.
 * Source: schemas.ErasureDrill
 * Type: Domain Entity (API)
 */
export const ErasureDrillEntitySchema = schemas.ErasureDrill;
export type ErasureDrillEntity = components["schemas"]["ErasureDrill"];
