/**
 * Handlers for Scan
 *
 * Generated by Handler Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: scans
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type { FastifyRequest, FastifyReply } from "fastify";
import type { ScansDomainModule } from "../dependencies/scans-ddd.dependencies.js";
import type { GetPdScanResultInput, ListPdScansInput, ScanTransactionProposalInput } from "@offhash/services/scans";
// Use cases are available via deps.useCases.<repoKey>.<verb>
// Execution context is automatically set up by route wrapper (wrapHandlerInExecutionContext)

/**
 * Handler for POST /v1/scans
 * Operation: scanTransactionProposal
 */
export async function scanTransactionProposal(
  request: FastifyRequest,
  reply: FastifyReply,
  deps: ScansDomainModule
): Promise<void> {
  // Security: orgId validated by setOrgContext hook; use case gets it from execution context
  const input: ScanTransactionProposalInput = {
    ...(request.body ?? {}),
  };
  const result = await deps.useCases.scans.get.execute(input);
  return reply.code(200).send(result);
}


/**
 * Handler for GET /v1/scans
 * Operation: listPdScans
 */
export async function listPdScans(
  request: FastifyRequest<{ Params: Record<string, string>; Querystring: { cursor?: string | string[], limit?: string | string[], decision?: string | string[], proposalRef?: string | string[] }; Body: unknown }>,
  reply: FastifyReply,
  deps: ScansDomainModule
): Promise<void> {
  // Security: orgId validated by setOrgContext hook; use case gets it from execution context
  const input: ListPdScansInput = {
    ...(request.query ?? {}),
  };
  const result = await deps.useCases.scans.list.execute(input);
  return reply.code(200).send(result);
}


/**
 * Handler for GET /v1/scans/{scanId}
 * Operation: getPdScanResult
 */
export async function getPdScanResult(
  request: FastifyRequest<{ Params: { scanId: string }; Querystring: Record<string, string | string[] | undefined>; Body: unknown }>,
  reply: FastifyReply,
  deps: ScansDomainModule
): Promise<void> {
  // Security: orgId validated by setOrgContext hook; use case gets it from execution context
  const input: GetPdScanResultInput = {
    scanId: request.params.scanId,
  };
  const result = await deps.useCases.scans.get.execute(input);
  return reply.code(200).send(result);
}


