/**
 * AntiPattern DTOs - Application DTOs
 *
 * Generated by DTO Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: antipatterns
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * AntiPattern DTOs
 *
 * DDD: Application DTOs for AntiPattern use cases.
 */

import type { FlagAntiPatternRequestInput, GetAntiPatternFlagParams, ListAntiPatternFlagsParams } from "@offhash/core/antipatterns/types";

export type ListAntiPatternFlagsInput = ListAntiPatternFlagsParams;

export type FlagAntiPatternInput = FlagAntiPatternRequestInput;

export type GetAntiPatternFlagInput = GetAntiPatternFlagParams;

export type ListAntiPatternFlagsOutput = {};

export type FlagAntiPatternOutput = {};

export type GetAntiPatternFlagOutput = {};
