/**
 * GetErasureJob handler tests
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: erasures
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


import { describe, it, expect, beforeEach, vi } from "vitest";
import { getErasureJob } from "@offhash/api-server/domains/erasures/handlers";
import type { ErasuresDDDDependencies } from "@offhash/api-server/domains/erasures";
import { createMockRequest, createMockReply, createMockDependencies, TEST_ORG_ID } from "@offhash/tests/shared";
import { ERASURES_USE_CASES } from "../__factories__/use-cases.js";

describe("GetErasureJob", () => {
  let mockRequest: ReturnType<typeof createMockRequest>;
  let mockReply: ReturnType<typeof createMockReply>;
  let mockDeps: ErasuresDDDDependencies;
  const orgId = TEST_ORG_ID;

  beforeEach(() => {
    mockRequest = createMockRequest({ orgId });
    mockReply = createMockReply();
    mockDeps = createMockDependencies<ErasuresDDDDependencies>(
      ERASURES_USE_CASES,
      {
        // Mock use case dependencies here
      }
    );
  });

  it("should return 200 with entity when found", async () => {
    const entity = { id: 'mock-id', orgId } as any;
    const useCaseResult = { data: entity, meta: { correlationId: "test", timestamp: new Date().toISOString() } };
    
    vi.spyOn(mockDeps.executeGetErasureJob, "execute").mockResolvedValue(useCaseResult);
    mockRequest.params = { jobId: entity.id };

    await getErasureJob(mockRequest, mockReply, mockDeps);

    expect(mockDeps.executeGetErasureJob.execute).toHaveBeenCalledWith(expect.objectContaining({ jobId: entity.id }));
    expect(mockReply.code).toHaveBeenCalledWith(200);
    expect(mockReply.send).toHaveBeenCalledWith(useCaseResult);
  });

  it("should return error when entity not found", async () => {
    const nonExistentId = "non-existent-id";
    mockRequest.params = { jobId: nonExistentId };
    
    vi.spyOn(mockDeps.executeGetErasureJob, "execute").mockRejectedValue(
      new Error("Entity not found")
    );

    await expect(
      getErasureJob(mockRequest, mockReply, mockDeps)
    ).rejects.toThrow();
  });

});
