/**
 * ListAntiPattern DTO Factory
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: antipatterns
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


import type { ListAntiPatternFlagsParams } from "@offhash/core/antipatterns";

export function createListAntiPatternRequest(overrides: Partial<ListAntiPatternFlagsParams> = {}) {
  const raw = {
    ...overrides,
  };

  return raw;
}
