/**
 * Compliance DTOs - Application DTOs
 *
 * Generated by DTO Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: reporting
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * Compliance DTOs
 *
 * DDD: Application DTOs for Compliance use cases.
 */

import type { GetFabricComplianceReportParams } from "@offhash/core/reporting/types";

export type GetFabricComplianceReportInput = GetFabricComplianceReportParams;

export type GetFabricComplianceReportOutput = {};
