/**
 * Repository interface for ConfigCertReview
 *
 * Generated by Repository Generator v1.0.0
 * Generator Version: 2.0.0
 * Domain: configcerts
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type {
  CreateReadRepository,
} from "../../_shared/repositories/_base-repository.js";

import type {
  ConfigCertReviewEntity
} from "../models/config-cert-review.entity.js";
import type {
  ListConfigCertReviewsParams,
  ConfigCertReview
} from "../types/index.js";
/**
 * ConfigCertReviewRepository Interface
 */
export interface ConfigCertReviewRepository extends CreateReadRepository<ConfigCertReviewEntity, ConfigCertReview, string, ListConfigCertReviewsParams> {

}
