/**
 * PolicyRepository Port - Application port interface
 *
 * Generated by Port Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: policies
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * PolicyRepository Port
 *
 * DDD: Application port for policyrepository operations.
 * This is an application-level abstraction, not a domain concept.
 * Implementations live in adapters layer.
 */

import type { CreateFabricPolicyInput, CreateFabricPolicyOutput, GetFabricPolicyInput, GetFabricPolicyOutput, ListFabricPoliciesInput, ListFabricPoliciesOutput, UpdateFabricPolicyInput, UpdateFabricPolicyOutput } from "../dto/policy.dto";
export interface PolicyRepository {
  listFabricPolicies(input: ListFabricPoliciesInput): Promise<ListFabricPoliciesOutput>;
  createFabricPolicy(input: CreateFabricPolicyInput): Promise<CreateFabricPolicyOutput>;
  getFabricPolicy(input: GetFabricPolicyInput): Promise<GetFabricPolicyOutput>;
  updateFabricPolicy(input: UpdateFabricPolicyInput): Promise<UpdateFabricPolicyOutput>;
}

export type { CreateFabricPolicyInput, CreateFabricPolicyOutput, GetFabricPolicyInput, GetFabricPolicyOutput, ListFabricPoliciesInput, ListFabricPoliciesOutput, UpdateFabricPolicyInput, UpdateFabricPolicyOutput } from "../dto/policy.dto";
