/**
 * ComplianceRepository Port - Application port interface
 *
 * Generated by Port Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: reporting
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * ComplianceRepository Port
 *
 * DDD: Application port for compliancerepository operations.
 * This is an application-level abstraction, not a domain concept.
 * Implementations live in adapters layer.
 */

import type { GetFabricComplianceReportInput, GetFabricComplianceReportOutput } from "../dto/compliance.dto";
export interface ComplianceRepository {
  getFabricComplianceReport(input: GetFabricComplianceReportInput): Promise<GetFabricComplianceReportOutput>;
}

export type { GetFabricComplianceReportInput, GetFabricComplianceReportOutput } from "../dto/compliance.dto";
