/**
 * DpiaExportRepository Port - Application port interface
 *
 * Generated by Port Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: reporting
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * DpiaExportRepository Port
 *
 * DDD: Application port for dpiaexportrepository operations.
 * This is an application-level abstraction, not a domain concept.
 * Implementations live in adapters layer.
 */

import type { CreateDpiaExportInput, CreateDpiaExportOutput } from "../dto/dpia-export.dto";
export interface DpiaExportRepository {
  createDpiaExport(input: CreateDpiaExportInput): Promise<CreateDpiaExportOutput>;
}

export type { CreateDpiaExportInput, CreateDpiaExportOutput } from "../dto/dpia-export.dto";
