/**
 * Use Case List
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: configcerts
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


/**
 * Configcerts Domain Use Cases
 * 
 * List of all use case names for the configcerts domain.
 * Used by createMockDependencies() to pre-create mocks.
 */

export const CONFIGCERTS_USE_CASES = [
  "executeCompleteConfigCertReview",
  "executeCreateConfigCertReview",
  "executeGetConfigCertReview",
  "executeListConfigCertReviews"
] as const;
