/**
 * ListPolicy DTO Factory
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: policies
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


import type { ListFabricPoliciesParams } from "@offhash/core/policies";

export function createListPolicyRequest(overrides: Partial<ListFabricPoliciesParams> = {}) {
  const raw = {
    ...overrides,
  };

  return raw;
}
