/**
 * ExecuteListEndorsementDecisions - Application use case
 *
 * Generated by Use Case Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: endorsement
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * ExecuteListEndorsementDecisions Use Case
 *
 * DDD: Application use case for list Decision.
 * Orchestrates the business flow using ports (interfaces).
 */

import type { ListEndorsementDecisionsInput, ListEndorsementDecisionsOutput } from "../dto/decision.dto";
import type { ExecutionContextService, IdGeneratorService } from "@offhash/services/_shared/index.js";
import type { DecisionRepository } from "../ports";

export class ExecuteListEndorsementDecisions {
  constructor(
    private readonly context: ExecutionContextService,
    private readonly idGenerator: IdGeneratorService,
    private readonly decision: DecisionRepository
  ) {}

  async execute(input: ListEndorsementDecisionsInput): Promise<ListEndorsementDecisionsOutput> {
    // Generate correlation ID for this request (domain-prefixed format: {domain_prefix}_{ulid})
    const correlationId = this.idGenerator.endId();

    // All field names extracted from OpenAPI spec: none
    // List entities via repository
    const result = await this.decision.listEndorsementDecisions({ ...input, orgId: this.context.getOrgId(), correlationId } as any);

    return result as ListEndorsementDecisionsOutput;
  }
}
