/**
 * ExecuteQuarantineEndorsementPeer - Application use case
 *
 * Generated by Use Case Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: endorsement
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * ExecuteQuarantineEndorsementPeer Use Case
 *
 * DDD: Application use case for get Quarantine.
 * Orchestrates the business flow using ports (interfaces).
 */

import type { QuarantineEndorsementPeerInput, QuarantineEndorsementPeerOutput } from "../dto/quarantine.dto";
import type { ExecutionContextService, IdGeneratorService } from "@offhash/services/_shared/index.js";
import type { QuarantineRepository } from "../ports";
import { NotFoundError, ValidationError } from "../errors";

export class ExecuteQuarantineEndorsementPeer {
  constructor(
    private readonly context: ExecutionContextService,
    private readonly idGenerator: IdGeneratorService,
    private readonly quarantine: QuarantineRepository
  ) {}

  async execute(input: QuarantineEndorsementPeerInput): Promise<QuarantineEndorsementPeerOutput> {
    // Generate correlation ID for this request (domain-prefixed format: {domain_prefix}_{ulid})
    const correlationId = this.idGenerator.endId();

    // All field names extracted from OpenAPI spec: reason
    // Validate input
    if (!input) {
      throw new ValidationError("Input is required");
    }
    if (!(input as any).peerId) {
      throw new ValidationError("peerId is required");
    }
    const peerId = (input as any).peerId;

    // Load entity via repository (pass correlation ID for response meta)
    const entity = await this.quarantine.quarantineEndorsementPeer({ peerId: peerId, orgId: this.context.getOrgId(), correlationId } as any);
    if (!entity) {
      throw new NotFoundError(`Entity not found: ${peerId}`);
    }

    return entity as QuarantineEndorsementPeerOutput;
  }
}
