/**
 * PolicyRepositoryAdapter - Port Adapter Implementation
 *
 * Generated by Port Adapter Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: policies
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * PolicyRepositoryAdapter
 *
 * DDD: Infrastructure adapter that implements PolicyRepository port.
 * Handles infrastructure concerns (HTTP, database, external APIs).
 * Encapsulates Ddb creation - api-server passes dynamoClient only.
 */

import type {
  PolicyRepository,
} from "@offhash/services/policies";
import type { AdapterDynamoDBClient } from "../_shared/dynamodb-client-types.js";
import { PolicyRepositoryDdb } from "./policy-repository.ddb.js";

/**
 * PolicyRepositoryAdapter
 *
 * Implements PolicyRepository port for infrastructure layer.
 */
export class PolicyRepositoryAdapter implements PolicyRepository {
  private readonly ddb: PolicyRepositoryDdb;

  constructor(
    private readonly dynamoClient: AdapterDynamoDBClient
  ) {
    this.ddb = new PolicyRepositoryDdb(this.dynamoClient);
  }

  async listFabricPolicies(input: Parameters<PolicyRepository['listFabricPolicies']>[0]): Promise<Awaited<ReturnType<PolicyRepository['listFabricPolicies']>>> {
    // Delegate to DynamoDB repository
    return await this.ddb.listFabricPolicies(input);
  }

  async createFabricPolicy(input: Parameters<PolicyRepository['createFabricPolicy']>[0]): Promise<Awaited<ReturnType<PolicyRepository['createFabricPolicy']>>> {
    // Delegate to DynamoDB repository
    return await this.ddb.createFabricPolicy(input);
  }

  async getFabricPolicy(input: Parameters<PolicyRepository['getFabricPolicy']>[0]): Promise<Awaited<ReturnType<PolicyRepository['getFabricPolicy']>>> {
    // Delegate to DynamoDB repository
    return await this.ddb.getFabricPolicy(input);
  }

  async updateFabricPolicy(input: Parameters<PolicyRepository['updateFabricPolicy']>[0]): Promise<Awaited<ReturnType<PolicyRepository['updateFabricPolicy']>>> {
    // Delegate to DynamoDB repository
    return await this.ddb.updateFabricPolicy(input);
  }
}
