/**
 * FlagAntiPattern handler tests
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: antipatterns
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


import { describe, it, expect, beforeEach, vi } from "vitest";
import { flagAntiPattern } from "@offhash/api-server/domains/antipatterns/handlers";
import type { AntipatternsDDDDependencies } from "@offhash/api-server/domains/antipatterns";
import { createMockRequest, createMockReply, createMockDependencies, TEST_ORG_ID } from "@offhash/tests/shared";
import { ANTIPATTERNS_USE_CASES } from "../__factories__/use-cases.js";

describe("FlagAntiPattern", () => {
  let mockRequest: ReturnType<typeof createMockRequest>;
  let mockReply: ReturnType<typeof createMockReply>;
  let mockDeps: AntipatternsDDDDependencies;
  const orgId = TEST_ORG_ID;

  beforeEach(() => {
    mockRequest = createMockRequest({ orgId });
    mockReply = createMockReply();
    mockDeps = createMockDependencies<AntipatternsDDDDependencies>(
      ANTIPATTERNS_USE_CASES,
      {
        // Mock use case dependencies here
      }
    );
  });

  it("should return 201 with created entity", async () => {
    const input = {} as any;
    const entity = { id: 'mock-id', orgId } as any;
    const useCaseResult = { data: entity, meta: { correlationId: "test", timestamp: new Date().toISOString() } };
    
    mockRequest.body = input;
    vi.spyOn(mockDeps.executeFlagAntiPattern, "execute").mockResolvedValue(useCaseResult);

    await flagAntiPattern(mockRequest, mockReply, mockDeps);

    expect(mockDeps.executeFlagAntiPattern.execute).toHaveBeenCalledWith(expect.anything());
    expect(mockReply.code).toHaveBeenCalledWith(201);
    expect(mockReply.send).toHaveBeenCalledWith(useCaseResult);
  });

});
