/**
 * GetAntiPatternFlag handler tests
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: antipatterns
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


import { describe, it, expect, beforeEach, vi } from "vitest";
import { getAntiPatternFlag } from "@offhash/api-server/domains/antipatterns/handlers";
import type { AntipatternsDDDDependencies } from "@offhash/api-server/domains/antipatterns";
import { createMockRequest, createMockReply, createMockDependencies, TEST_ORG_ID } from "@offhash/tests/shared";
import { ANTIPATTERNS_USE_CASES } from "../__factories__/use-cases.js";

describe("GetAntiPatternFlag", () => {
  let mockRequest: ReturnType<typeof createMockRequest>;
  let mockReply: ReturnType<typeof createMockReply>;
  let mockDeps: AntipatternsDDDDependencies;
  const orgId = TEST_ORG_ID;

  beforeEach(() => {
    mockRequest = createMockRequest({ orgId });
    mockReply = createMockReply();
    mockDeps = createMockDependencies<AntipatternsDDDDependencies>(
      ANTIPATTERNS_USE_CASES,
      {
        // Mock use case dependencies here
      }
    );
  });

  it("should return 200 with entity when found", async () => {
    const entity = { id: 'mock-id', orgId } as any;
    const useCaseResult = { data: entity, meta: { correlationId: "test", timestamp: new Date().toISOString() } };
    
    vi.spyOn(mockDeps.executeGetAntiPatternFlag, "execute").mockResolvedValue(useCaseResult);
    mockRequest.params = { flagId: entity.id };

    await getAntiPatternFlag(mockRequest, mockReply, mockDeps);

    expect(mockDeps.executeGetAntiPatternFlag.execute).toHaveBeenCalledWith(expect.objectContaining({ flagId: entity.id }));
    expect(mockReply.code).toHaveBeenCalledWith(200);
    expect(mockReply.send).toHaveBeenCalledWith(useCaseResult);
  });

  it("should return error when entity not found", async () => {
    const nonExistentId = "non-existent-id";
    mockRequest.params = { flagId: nonExistentId };
    
    vi.spyOn(mockDeps.executeGetAntiPatternFlag, "execute").mockRejectedValue(
      new Error("Entity not found")
    );

    await expect(
      getAntiPatternFlag(mockRequest, mockReply, mockDeps)
    ).rejects.toThrow();
  });

});
