/**
 * Handler tests barrel export
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: antipatterns
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

export * from "./flag-anti-pattern.handler.test.js";
export * from "./get-anti-pattern-flag.handler.test.js";
export * from "./list-anti-pattern-flags.handler.test.js";
