/**
 * Handlers for AcceptRisk
 *
 * Generated by Handler Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: antipatterns
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type { FastifyRequest, FastifyReply } from "fastify";
import type { AntipatternsDomainModule } from "../dependencies/antipatterns-ddd.dependencies.js";
import type { AcceptAntiPatternRiskInput } from "@offhash/services/antipatterns";
// Use cases are available via deps.useCases.<repoKey>.<verb>
// Execution context is automatically set up by route wrapper (wrapHandlerInExecutionContext)

/**
 * Handler for POST /v1/anti-patterns/{flagId}/accept-risk
 * Operation: acceptAntiPatternRisk
 */
export async function acceptAntiPatternRisk(
  request: FastifyRequest<{ Params: { flagId: string }; Querystring: Record<string, string | string[] | undefined>; Body: unknown }>,
  reply: FastifyReply,
  deps: AntipatternsDomainModule
): Promise<void> {
  // Security: orgId validated by setOrgContext hook; use case gets it from execution context
  const input: AcceptAntiPatternRiskInput = {
    flagId: request.params.flagId,
    ...(request.body ?? {}),
  };
  const result = await deps.useCases.acceptRisks.get.execute(input);
  return reply.code(200).send(result);
}


