/**
 * ConfigCertReview Entity Factory
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: configcerts
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


import { faker } from "@faker-js/faker";
import type { ConfigCertReviewEntity } from "@offhash/core/configcerts/models/index.js";
import { configcertsSchemas } from "@offhash/core/configcerts";
import { ulid } from "ulid";

// Domain prefix from OpenAPI spec info.x-domain
const DOMAIN_PREFIX = "cfg";

export function createConfigCertReview(overrides: Partial<ConfigCertReviewEntity> = {}) {
  const raw = {
    id: overrides.id ?? `${DOMAIN_PREFIX}_${ulid().toLowerCase()}`,
    createdAt: overrides.createdAt ?? new Date().toISOString(),
    updatedAt: overrides.updatedAt ?? new Date().toISOString(),
    networkId: overrides.networkId ?? `net_${ulid().toLowerCase()}`,
    reviewId: overrides.reviewId ?? `cfg_${ulid().toLowerCase()}`,
    scheduledAt: overrides.scheduledAt ?? new Date().toISOString(),
    status: overrides.status ?? "scheduled",
    subjectBoundCertCount: overrides.subjectBoundCertCount ?? faker.number.int({ min: 1, max: 100 }),
    ...overrides,
  };

  return configcertsSchemas.ConfigCertReview.parse(raw);
}

export function configCertReviewBatch(n = 3, overrides = {}) {
  return Array.from({ length: n }, () => createConfigCertReview(overrides));
}
