/**
 * Reporting DDD Dependencies - Composition root
 *
 * Generated by Dependencies Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: reporting
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * Reporting Domain Module - Composition root
 *
 * DDD: Composition root for reporting domain. Exposes repos (ports) and use cases
 * grouped by aggregate. No orgId at build time — use execution context at call time.
 */

import {
  ComplianceRepositoryAdapter,
  DpiaExportRepositoryAdapter,
} from "@offhash/adapters/reporting";
import { getIdGeneratorService } from "@offhash/adapters";
import type { AdapterDynamoDBClient } from "@offhash/adapters";
import { executionContextService } from "../../../lib/execution-context.service.js";
// Use-case constructors (concrete)
import {
  ExecuteCreateDpiaExport,
  ExecuteGetFabricComplianceReport,
} from "@offhash/services/reporting/usecases";
// Ports (interfaces)
import type {
  ComplianceRepository,
  DpiaExportRepository,
} from "@offhash/services/reporting/ports";

export interface ReportingDomainModule {
  repos: {
    compliances: ComplianceRepository;
    dpiaExports: DpiaExportRepository;
  };
  useCases: {
    compliances: {
      get: ExecuteGetFabricComplianceReport;
    };
    dpiaExports: {
      create: ExecuteCreateDpiaExport;
    };
  };
}

export function buildReportingDomainModule(
  dynamoClient: AdapterDynamoDBClient,
): ReportingDomainModule {
  // Adapters implementing ports (adapters encapsulate Ddb)
  const repos = (() => {
    const obj: {
      compliances?: ComplianceRepository;
      dpiaExports?: DpiaExportRepository;
    } = {};

    obj.compliances = new ComplianceRepositoryAdapter(dynamoClient);
    obj.dpiaExports = new DpiaExportRepositoryAdapter(dynamoClient);
    return {
      compliances: obj.compliances!,
      dpiaExports: obj.dpiaExports!,
    };
  })();

  const executionContext = executionContextService;
  const idGenerator = getIdGeneratorService();

  // Use cases depend only on ports (repos.*)
  const useCases = {
    compliances: {
      get: new ExecuteGetFabricComplianceReport(executionContext, idGenerator, repos.compliances),
    },
    dpiaExports: {
      create: new ExecuteCreateDpiaExport(executionContext, idGenerator, repos.dpiaExports),
    },
  };
  return { repos, useCases: useCases as ReportingDomainModule["useCases"] };
}
