/**
 * AcceptRiskRepositoryAdapter - Port Adapter Implementation
 *
 * Generated by Port Adapter Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: antipatterns
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * AcceptRiskRepositoryAdapter
 *
 * DDD: Infrastructure adapter that implements AcceptRiskRepository port.
 * Handles infrastructure concerns (HTTP, database, external APIs).
 * Encapsulates Ddb creation - api-server passes dynamoClient only.
 */

import type {
  AcceptRiskRepository,
} from "@offhash/services/antipatterns";
import type { AdapterDynamoDBClient } from "../_shared/dynamodb-client-types.js";
import { AcceptRiskRepositoryDdb } from "./accept-risk-repository.ddb.js";

/**
 * AcceptRiskRepositoryAdapter
 *
 * Implements AcceptRiskRepository port for infrastructure layer.
 */
export class AcceptRiskRepositoryAdapter implements AcceptRiskRepository {
  private readonly ddb: AcceptRiskRepositoryDdb;

  constructor(
    private readonly dynamoClient: AdapterDynamoDBClient
  ) {
    this.ddb = new AcceptRiskRepositoryDdb(this.dynamoClient);
  }

  async acceptAntiPatternRisk(input: Parameters<AcceptRiskRepository['acceptAntiPatternRisk']>[0]): Promise<Awaited<ReturnType<AcceptRiskRepository['acceptAntiPatternRisk']>>> {
    // Delegate to DynamoDB repository
    return await this.ddb.acceptAntiPatternRisk(input);
  }
}
