/**
 * AntiPatternRepositoryAdapter - Port Adapter Implementation
 *
 * Generated by Port Adapter Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: antipatterns
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * AntiPatternRepositoryAdapter
 *
 * DDD: Infrastructure adapter that implements AntiPatternRepository port.
 * Handles infrastructure concerns (HTTP, database, external APIs).
 * Encapsulates Ddb creation - api-server passes dynamoClient only.
 */

import type {
  AntiPatternRepository,
} from "@offhash/services/antipatterns";
import type { AdapterDynamoDBClient } from "../_shared/dynamodb-client-types.js";
import { AntiPatternRepositoryDdb } from "./anti-pattern-repository.ddb.js";

/**
 * AntiPatternRepositoryAdapter
 *
 * Implements AntiPatternRepository port for infrastructure layer.
 */
export class AntiPatternRepositoryAdapter implements AntiPatternRepository {
  private readonly ddb: AntiPatternRepositoryDdb;

  constructor(
    private readonly dynamoClient: AdapterDynamoDBClient
  ) {
    this.ddb = new AntiPatternRepositoryDdb(this.dynamoClient);
  }

  async listAntiPatternFlags(input: Parameters<AntiPatternRepository['listAntiPatternFlags']>[0]): Promise<Awaited<ReturnType<AntiPatternRepository['listAntiPatternFlags']>>> {
    // Delegate to DynamoDB repository
    return await this.ddb.listAntiPatternFlags(input);
  }

  async flagAntiPattern(input: Parameters<AntiPatternRepository['flagAntiPattern']>[0]): Promise<Awaited<ReturnType<AntiPatternRepository['flagAntiPattern']>>> {
    // Delegate to DynamoDB repository
    return await this.ddb.flagAntiPattern(input);
  }

  async getAntiPatternFlag(input: Parameters<AntiPatternRepository['getAntiPatternFlag']>[0]): Promise<Awaited<ReturnType<AntiPatternRepository['getAntiPatternFlag']>>> {
    // Delegate to DynamoDB repository
    return await this.ddb.getAntiPatternFlag(input);
  }
}
