/**
 * Routes index
 *
 * Generated by Routes Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: endorsement
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

export { decisionRoutes } from "./decision.routes.js";
export { peerRoutes } from "./peer.routes.js";
export { quarantineRoutes } from "./quarantine.routes.js";
