/**
 * Routes for Quarantine
 *
 * Generated by Routes Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: endorsement
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type { FastifyInstance, FastifyRequest, FastifyReply } from "fastify";
import { getDependencyContainer } from "../../../infrastructure/dependency-container.js";
import { quarantineEndorsementPeer } from "../handlers/quarantine.handlers.js";
import { wrapHandlerInExecutionContext } from "../../../lib/execution-context-wrapper.js";

// Fastify types are available globally
export async function quarantineRoutes(fastify: FastifyInstance) {
  // POST /v1/endorsement/peers/{peerId}/quarantine (unscoped; scope set for security middleware)
  fastify.post(
    "/v1/endorsement/peers/:peerId/quarantine",
    { config: { scope: 'public' } },
    async (request: FastifyRequest<{ Params: { peerId: string }; Querystring: Record<string, string | string[] | undefined>; Body: unknown }>, reply: FastifyReply) => {
      await wrapHandlerInExecutionContext(request, async () => {
        const deps = getDependencyContainer().getEndorsementDependenciesForRequest();
        await quarantineEndorsementPeer(request, reply, deps);
      });
    }
  );


}
