/**
 * ExecuteGetAntiPatternFlag - Application use case
 *
 * Generated by Use Case Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: antipatterns
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * ExecuteGetAntiPatternFlag Use Case
 *
 * DDD: Application use case for get AntiPattern.
 * Orchestrates the business flow using ports (interfaces).
 */

import type { GetAntiPatternFlagInput, GetAntiPatternFlagOutput } from "../dto/anti-pattern.dto";
import type { ExecutionContextService, IdGeneratorService } from "@offhash/services/_shared/index.js";
import type { AntiPatternRepository } from "../ports";
import { NotFoundError, ValidationError } from "../errors";

export class ExecuteGetAntiPatternFlag {
  constructor(
    private readonly context: ExecutionContextService,
    private readonly idGenerator: IdGeneratorService,
    private readonly antiPattern: AntiPatternRepository
  ) {}

  async execute(input: GetAntiPatternFlagInput): Promise<GetAntiPatternFlagOutput> {
    // Generate correlation ID for this request (domain-prefixed format: {domain_prefix}_{ulid})
    const correlationId = this.idGenerator.apnId();

    // All field names extracted from OpenAPI spec: none
    // Validate input
    if (!input) {
      throw new ValidationError("Input is required");
    }
    if (!(input as any).flagId) {
      throw new ValidationError("flagId is required");
    }
    const flagId = (input as any).flagId;

    // Load entity via repository (pass correlation ID for response meta)
    const entity = await this.antiPattern.getAntiPatternFlag({ flagId: flagId, orgId: this.context.getOrgId(), correlationId } as any);
    if (!entity) {
      throw new NotFoundError(`Entity not found: ${flagId}`);
    }

    return entity as GetAntiPatternFlagOutput;
  }
}
