/**
 * ExecuteListAntiPatternFlags - Application use case
 *
 * Generated by Use Case Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: antipatterns
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * ExecuteListAntiPatternFlags Use Case
 *
 * DDD: Application use case for list AntiPattern.
 * Orchestrates the business flow using ports (interfaces).
 */

import type { ListAntiPatternFlagsInput, ListAntiPatternFlagsOutput } from "../dto/anti-pattern.dto";
import type { ExecutionContextService, IdGeneratorService } from "@offhash/services/_shared/index.js";
import type { AntiPatternRepository } from "../ports";

export class ExecuteListAntiPatternFlags {
  constructor(
    private readonly context: ExecutionContextService,
    private readonly idGenerator: IdGeneratorService,
    private readonly antiPattern: AntiPatternRepository
  ) {}

  async execute(input: ListAntiPatternFlagsInput): Promise<ListAntiPatternFlagsOutput> {
    // Generate correlation ID for this request (domain-prefixed format: {domain_prefix}_{ulid})
    const correlationId = this.idGenerator.apnId();

    // All field names extracted from OpenAPI spec: none
    // List entities via repository
    const result = await this.antiPattern.listAntiPatternFlags({ ...input, orgId: this.context.getOrgId(), correlationId } as any);

    return result as ListAntiPatternFlagsOutput;
  }
}
