/**
 * Use Case List
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: hashes
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


/**
 * Hashes Domain Use Cases
 * 
 * List of all use case names for the hashes domain.
 * Used by createMockDependencies() to pre-create mocks.
 */

export const HASHES_USE_CASES = [
  "executeGetSaltedHashRecord",
  "executeListSaltedHashRecords",
  "executeRegisterSaltedHash"
] as const;
