/**
 * ScanRepository Port - Application port interface
 *
 * Generated by Port Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: scans
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * ScanRepository Port
 *
 * DDD: Application port for scanrepository operations.
 * This is an application-level abstraction, not a domain concept.
 * Implementations live in adapters layer.
 */

import type { GetPdScanResultInput, GetPdScanResultOutput, ListPdScansInput, ListPdScansOutput, ScanTransactionProposalInput, ScanTransactionProposalOutput } from "../dto/scan.dto";
export interface ScanRepository {
  scanTransactionProposal(input: ScanTransactionProposalInput): Promise<ScanTransactionProposalOutput>;
  listPdScans(input: ListPdScansInput): Promise<ListPdScansOutput>;
  getPdScanResult(input: GetPdScanResultInput): Promise<GetPdScanResultOutput>;
}

export type { GetPdScanResultInput, GetPdScanResultOutput, ListPdScansInput, ListPdScansOutput, ScanTransactionProposalInput, ScanTransactionProposalOutput } from "../dto/scan.dto";
