/**
 * CreateErasureDrill handler tests
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: erasures
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


import { describe, it, expect, beforeEach, vi } from "vitest";
import { createErasureDrill } from "@offhash/api-server/domains/erasures/handlers";
import type { ErasuresDDDDependencies } from "@offhash/api-server/domains/erasures";
import { createErasureDrill as createErasureDrillEntity } from "@offhash/factories/erasures";
import { createMockRequest, createMockReply, createMockDependencies, TEST_ORG_ID } from "@offhash/tests/shared";
import { ERASURES_USE_CASES } from "../__factories__/use-cases.js";

describe("CreateErasureDrill", () => {
  let mockRequest: ReturnType<typeof createMockRequest>;
  let mockReply: ReturnType<typeof createMockReply>;
  let mockDeps: ErasuresDDDDependencies;
  const orgId = TEST_ORG_ID;

  beforeEach(() => {
    mockRequest = createMockRequest({ orgId });
    mockReply = createMockReply();
    mockDeps = createMockDependencies<ErasuresDDDDependencies>(
      ERASURES_USE_CASES,
      {
        // Mock use case dependencies here
      }
    );
  });

  it("should return 201 with created entity", async () => {
    const input = {} as any;
    const entity = createErasureDrillEntity({ orgId });
    const useCaseResult = { data: entity, meta: { correlationId: "test", timestamp: new Date().toISOString() } };
    
    mockRequest.body = input;
    vi.spyOn(mockDeps.executeCreateErasureDrill, "execute").mockResolvedValue(useCaseResult);

    await createErasureDrill(mockRequest, mockReply, mockDeps);

    expect(mockDeps.executeCreateErasureDrill.execute).toHaveBeenCalledWith(expect.anything());
    expect(mockReply.code).toHaveBeenCalledWith(201);
    expect(mockReply.send).toHaveBeenCalledWith(useCaseResult);
  });

});
