/**
 * ConfigCertReview DTOs - Application DTOs
 *
 * Generated by DTO Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: configcerts
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * ConfigCertReview DTOs
 *
 * DDD: Application DTOs for ConfigCertReview use cases.
 */

import type { CreateConfigCertReviewRequestInput, GetConfigCertReviewParams, ListConfigCertReviewsParams } from "@offhash/core/configcerts/types";

export type ListConfigCertReviewsInput = ListConfigCertReviewsParams;

export type CreateConfigCertReviewInput = CreateConfigCertReviewRequestInput;

export type GetConfigCertReviewInput = GetConfigCertReviewParams;

export type ListConfigCertReviewsOutput = {};

export type CreateConfigCertReviewOutput = {};

export type GetConfigCertReviewOutput = {};
