/**
 * ExecuteSimulateFabricPolicy - Application use case
 *
 * Generated by Use Case Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: policies
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * ExecuteSimulateFabricPolicy Use Case
 *
 * DDD: Application use case for get Simulate.
 * Orchestrates the business flow using ports (interfaces).
 */

import type { SimulateFabricPolicyInput, SimulateFabricPolicyOutput } from "../dto/simulate.dto";
import type { ExecutionContextService, IdGeneratorService } from "@offhash/services/_shared/index.js";
import type { SimulateRepository } from "../ports";
import { NotFoundError, ValidationError } from "../errors";

export class ExecuteSimulateFabricPolicy {
  constructor(
    private readonly context: ExecutionContextService,
    private readonly idGenerator: IdGeneratorService,
    private readonly simulate: SimulateRepository
  ) {}

  async execute(input: SimulateFabricPolicyInput): Promise<SimulateFabricPolicyOutput> {
    // Generate correlation ID for this request (domain-prefixed format: {domain_prefix}_{ulid})
    const correlationId = this.idGenerator.polId();

    // All field names extracted from OpenAPI spec: fields, proposalRef
    // Validate input
    if (!input) {
      throw new ValidationError("Input is required");
    }
    if (!(input as any).policyId) {
      throw new ValidationError("policyId is required");
    }
    const policyId = (input as any).policyId;

    // Load entity via repository (pass correlation ID for response meta)
    const entity = await this.simulate.simulateFabricPolicy({ policyId: policyId, orgId: this.context.getOrgId(), correlationId } as any);
    if (!entity) {
      throw new NotFoundError(`Entity not found: ${policyId}`);
    }

    return entity as SimulateFabricPolicyOutput;
  }
}
