/**
 * ExecuteListFabricPolicies - Application use case
 *
 * Generated by Use Case Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: policies
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * ExecuteListFabricPolicies Use Case
 *
 * DDD: Application use case for list Policy.
 * Orchestrates the business flow using ports (interfaces).
 */

import type { ListFabricPoliciesInput, ListFabricPoliciesOutput } from "../dto/policy.dto";
import type { ExecutionContextService, IdGeneratorService } from "@offhash/services/_shared/index.js";
import type { PolicyRepository } from "../ports";

export class ExecuteListFabricPolicies {
  constructor(
    private readonly context: ExecutionContextService,
    private readonly idGenerator: IdGeneratorService,
    private readonly policy: PolicyRepository
  ) {}

  async execute(input: ListFabricPoliciesInput): Promise<ListFabricPoliciesOutput> {
    // Generate correlation ID for this request (domain-prefixed format: {domain_prefix}_{ulid})
    const correlationId = this.idGenerator.polId();

    // All field names extracted from OpenAPI spec: none
    // List entities via repository
    const result = await this.policy.listFabricPolicies({ ...input, orgId: this.context.getOrgId(), correlationId } as any);

    return result as ListFabricPoliciesOutput;
  }
}
