/**
 * Main Services Package Index
 *
 * Generated by Services Main Index Generator v1.0.0
 * Generator Version: 2.0.0
 * Domain: identity
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * Services Package - Main Barrel Export
 *
 * Central export point for all application services (use cases, ports, DTOs, policies, errors)
 * Organized by domain for easy importing
 *
 * Usage:
 *   // Namespace imports (recommended)
 *   import { activity, ai, conversation } from "@offhash/services";
 *   const { usecases, dto, ports } = activity;
 *
 *   // Direct imports from domain
 *   import { ExecuteCreateEventUseCase } from "@offhash/services/activity";
 *   
 *   // Shared services
 *   import { executionContextService } from "@offhash/services";
 */

// ============================================================================
// SHARED SERVICES EXPORTS
// ============================================================================
export { executionContextService } from "./_shared/index.js";

// ============================================================================
// DOMAIN EXPORTS (using namespace to avoid duplicate type conflicts)
// ============================================================================
// Export domains as namespaces to prevent TS2308 errors from duplicate exports
// of shared types across domains

import * as _antipatterns from "./antipatterns/index.js";
import * as _configcerts from "./configcerts/index.js";
import * as _endorsement from "./endorsement/index.js";
import * as _erasures from "./erasures/index.js";
import * as _hashes from "./hashes/index.js";
import * as _identity from "./identity/index.js";
import * as _policies from "./policies/index.js";
import * as _reporting from "./reporting/index.js";
import * as _scans from "./scans/index.js";

// Export as namespaces
export const antipatterns = _antipatterns;
export const configcerts = _configcerts;
export const endorsement = _endorsement;
export const erasures = _erasures;
export const hashes = _hashes;
export const identity = _identity;
export const policies = _policies;
export const reporting = _reporting;
export const scans = _scans;
