/**
 * Endorsement DDD Dependencies - Composition root
 *
 * Generated by Dependencies Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: endorsement
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * Endorsement Domain Module - Composition root
 *
 * DDD: Composition root for endorsement domain. Exposes repos (ports) and use cases
 * grouped by aggregate. No orgId at build time — use execution context at call time.
 */

import {
  DecisionRepositoryAdapter,
  PeerRepositoryAdapter,
  QuarantineRepositoryAdapter,
} from "@offhash/adapters/endorsement";
import { getIdGeneratorService } from "@offhash/adapters";
import type { AdapterDynamoDBClient } from "@offhash/adapters";
import { executionContextService } from "../../../lib/execution-context.service.js";
// Use-case constructors (concrete)
import {
  ExecuteGetEndorsementPeer,
  ExecuteListEndorsementDecisions,
  ExecuteListEndorsementPeers,
  ExecuteQuarantineEndorsementPeer,
} from "@offhash/services/endorsement/usecases";
// Ports (interfaces)
import type {
  DecisionRepository,
  PeerRepository,
  QuarantineRepository,
} from "@offhash/services/endorsement/ports";

export interface EndorsementDomainModule {
  repos: {
    decisions: DecisionRepository;
    peers: PeerRepository;
    quarantines: QuarantineRepository;
  };
  useCases: {
    decisions: {
      list: ExecuteListEndorsementDecisions;
    };
    peers: {
      get: ExecuteGetEndorsementPeer;
      list: ExecuteListEndorsementPeers;
    };
    quarantines: {
      get: ExecuteQuarantineEndorsementPeer;
    };
  };
}

export function buildEndorsementDomainModule(
  dynamoClient: AdapterDynamoDBClient,
): EndorsementDomainModule {
  // Adapters implementing ports (adapters encapsulate Ddb)
  const repos = (() => {
    const obj: {
      decisions?: DecisionRepository;
      peers?: PeerRepository;
      quarantines?: QuarantineRepository;
    } = {};

    obj.decisions = new DecisionRepositoryAdapter(dynamoClient);
    obj.peers = new PeerRepositoryAdapter(dynamoClient);
    obj.quarantines = new QuarantineRepositoryAdapter(dynamoClient);
    return {
      decisions: obj.decisions!,
      peers: obj.peers!,
      quarantines: obj.quarantines!,
    };
  })();

  const executionContext = executionContextService;
  const idGenerator = getIdGeneratorService();

  // Use cases depend only on ports (repos.*)
  const useCases = {
    decisions: {
      list: new ExecuteListEndorsementDecisions(executionContext, idGenerator, repos.decisions),
    },
    peers: {
      get: new ExecuteGetEndorsementPeer(executionContext, idGenerator, repos.peers),
      list: new ExecuteListEndorsementPeers(executionContext, idGenerator, repos.peers),
    },
    quarantines: {
      get: new ExecuteQuarantineEndorsementPeer(executionContext, idGenerator, repos.quarantines),
    },
  };
  return { repos, useCases: useCases as EndorsementDomainModule["useCases"] };
}
