/**
 * ConfigCertReviewRepositoryAdapter - Port Adapter Implementation
 *
 * Generated by Port Adapter Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: configcerts
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * ConfigCertReviewRepositoryAdapter
 *
 * DDD: Infrastructure adapter that implements ConfigCertReviewRepository port.
 * Handles infrastructure concerns (HTTP, database, external APIs).
 * Encapsulates Ddb creation - api-server passes dynamoClient only.
 */

import type {
  ConfigCertReviewRepository,
} from "@offhash/services/configcerts";
import type { AdapterDynamoDBClient } from "../_shared/dynamodb-client-types.js";
import { ConfigCertReviewRepositoryDdb } from "./config-cert-review-repository.ddb.js";

/**
 * ConfigCertReviewRepositoryAdapter
 *
 * Implements ConfigCertReviewRepository port for infrastructure layer.
 */
export class ConfigCertReviewRepositoryAdapter implements ConfigCertReviewRepository {
  private readonly ddb: ConfigCertReviewRepositoryDdb;

  constructor(
    private readonly dynamoClient: AdapterDynamoDBClient
  ) {
    this.ddb = new ConfigCertReviewRepositoryDdb(this.dynamoClient);
  }

  async listConfigCertReviews(input: Parameters<ConfigCertReviewRepository['listConfigCertReviews']>[0]): Promise<Awaited<ReturnType<ConfigCertReviewRepository['listConfigCertReviews']>>> {
    // Delegate to DynamoDB repository
    return await this.ddb.listConfigCertReviews(input);
  }

  async createConfigCertReview(input: Parameters<ConfigCertReviewRepository['createConfigCertReview']>[0]): Promise<Awaited<ReturnType<ConfigCertReviewRepository['createConfigCertReview']>>> {
    // Delegate to DynamoDB repository
    return await this.ddb.createConfigCertReview(input);
  }

  async getConfigCertReview(input: Parameters<ConfigCertReviewRepository['getConfigCertReview']>[0]): Promise<Awaited<ReturnType<ConfigCertReviewRepository['getConfigCertReview']>>> {
    // Delegate to DynamoDB repository
    return await this.ddb.getConfigCertReview(input);
  }
}
