/**
 * DynamoDB repository adapters barrel export
 *
 * Generated by Port Adapter Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: configcerts
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

export * from "./complete-repository.ddb.js";
export * from "./config-cert-review-repository.ddb.js";
export * from "./complete-repository.adapter.js";
export * from "./config-cert-review-repository.adapter.js";
