/**
 * ErasureRepositoryAdapter - Port Adapter Implementation
 *
 * Generated by Port Adapter Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: erasures
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * ErasureRepositoryAdapter
 *
 * DDD: Infrastructure adapter that implements ErasureRepository port.
 * Handles infrastructure concerns (HTTP, database, external APIs).
 * Encapsulates Ddb creation - api-server passes dynamoClient only.
 */

import type {
  ErasureRepository,
} from "@offhash/services/erasures";
import type { AdapterDynamoDBClient } from "../_shared/dynamodb-client-types.js";
import { ErasureRepositoryDdb } from "./erasure-repository.ddb.js";

/**
 * ErasureRepositoryAdapter
 *
 * Implements ErasureRepository port for infrastructure layer.
 */
export class ErasureRepositoryAdapter implements ErasureRepository {
  private readonly ddb: ErasureRepositoryDdb;

  constructor(
    private readonly dynamoClient: AdapterDynamoDBClient
  ) {
    this.ddb = new ErasureRepositoryDdb(this.dynamoClient);
  }

  async listErasureJobs(input: Parameters<ErasureRepository['listErasureJobs']>[0]): Promise<Awaited<ReturnType<ErasureRepository['listErasureJobs']>>> {
    // Delegate to DynamoDB repository
    return await this.ddb.listErasureJobs(input);
  }

  async executePdErasure(input: Parameters<ErasureRepository['executePdErasure']>[0]): Promise<Awaited<ReturnType<ErasureRepository['executePdErasure']>>> {
    // Delegate to DynamoDB repository
    return await this.ddb.executePdErasure(input);
  }

  async getErasureJob(input: Parameters<ErasureRepository['getErasureJob']>[0]): Promise<Awaited<ReturnType<ErasureRepository['getErasureJob']>>> {
    // Delegate to DynamoDB repository
    return await this.ddb.getErasureJob(input);
  }
}
