/**
 * ErasureDrillRepositoryAdapter - Port Adapter Implementation
 *
 * Generated by Port Adapter Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: erasures
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * ErasureDrillRepositoryAdapter
 *
 * DDD: Infrastructure adapter that implements ErasureDrillRepository port.
 * Handles infrastructure concerns (HTTP, database, external APIs).
 * Encapsulates Ddb creation - api-server passes dynamoClient only.
 */

import type {
  ErasureDrillRepository,
} from "@offhash/services/erasures";
import type { AdapterDynamoDBClient } from "../_shared/dynamodb-client-types.js";
import { ErasureDrillRepositoryDdb } from "./erasure-drill-repository.ddb.js";

/**
 * ErasureDrillRepositoryAdapter
 *
 * Implements ErasureDrillRepository port for infrastructure layer.
 */
export class ErasureDrillRepositoryAdapter implements ErasureDrillRepository {
  private readonly ddb: ErasureDrillRepositoryDdb;

  constructor(
    private readonly dynamoClient: AdapterDynamoDBClient
  ) {
    this.ddb = new ErasureDrillRepositoryDdb(this.dynamoClient);
  }

  async listErasureDrills(input: Parameters<ErasureDrillRepository['listErasureDrills']>[0]): Promise<Awaited<ReturnType<ErasureDrillRepository['listErasureDrills']>>> {
    // Delegate to DynamoDB repository
    return await this.ddb.listErasureDrills(input);
  }

  async createErasureDrill(input: Parameters<ErasureDrillRepository['createErasureDrill']>[0]): Promise<Awaited<ReturnType<ErasureDrillRepository['createErasureDrill']>>> {
    // Delegate to DynamoDB repository
    return await this.ddb.createErasureDrill(input);
  }

  async getErasureDrill(input: Parameters<ErasureDrillRepository['getErasureDrill']>[0]): Promise<Awaited<ReturnType<ErasureDrillRepository['getErasureDrill']>>> {
    // Delegate to DynamoDB repository
    return await this.ddb.getErasureDrill(input);
  }
}
