/**
 * ErasureDrill DTOs - Application DTOs
 *
 * Generated by DTO Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: erasures
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * ErasureDrill DTOs
 *
 * DDD: Application DTOs for ErasureDrill use cases.
 */

import type { CreateErasureDrillRequestInput, GetErasureDrillParams, ListErasureDrillsParams } from "@offhash/core/erasures/types";

export type ListErasureDrillsInput = ListErasureDrillsParams;

export type CreateErasureDrillInput = CreateErasureDrillRequestInput;

export type GetErasureDrillInput = GetErasureDrillParams;

export type ListErasureDrillsOutput = {};

export type CreateErasureDrillOutput = {};

export type GetErasureDrillOutput = {};
