/**
 * Erasure DTOs - Application DTOs
 *
 * Generated by DTO Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: erasures
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * Erasure DTOs
 *
 * DDD: Application DTOs for Erasure use cases.
 */

import type { ExecutePdErasureRequestInput, GetErasureJobParams, ListErasureJobsParams } from "@offhash/core/erasures/types";

export type ListErasureJobsInput = ListErasureJobsParams;

export type ExecutePdErasureInput = ExecutePdErasureRequestInput;

export type GetErasureJobInput = GetErasureJobParams;

export type ListErasureJobsOutput = {};

export type ExecutePdErasureOutput = {};

export type GetErasureJobOutput = {};
