/**
 * ExecuteGetSaltedHashRecord - Application use case
 *
 * Generated by Use Case Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: hashes
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * ExecuteGetSaltedHashRecord Use Case
 *
 * DDD: Application use case for get HashRecord.
 * Orchestrates the business flow using ports (interfaces).
 */

import type { GetSaltedHashRecordInput, GetSaltedHashRecordOutput } from "../dto/hash-record.dto";
import type { ExecutionContextService, IdGeneratorService } from "@offhash/services/_shared/index.js";
import type { HashRecordRepository } from "../ports";
import { NotFoundError, ValidationError } from "../errors";

export class ExecuteGetSaltedHashRecord {
  constructor(
    private readonly context: ExecutionContextService,
    private readonly idGenerator: IdGeneratorService,
    private readonly hashRecord: HashRecordRepository
  ) {}

  async execute(input: GetSaltedHashRecordInput): Promise<GetSaltedHashRecordOutput> {
    // Generate correlation ID for this request (domain-prefixed format: {domain_prefix}_{ulid})
    const correlationId = this.idGenerator.hshId();

    // All field names extracted from OpenAPI spec: none
    // Validate input
    if (!input) {
      throw new ValidationError("Input is required");
    }
    if (!(input as any).hashId) {
      throw new ValidationError("hashId is required");
    }
    const hashId = (input as any).hashId;

    // Load entity via repository (pass correlation ID for response meta)
    const entity = await this.hashRecord.getSaltedHashRecord({ hashId: hashId, orgId: this.context.getOrgId(), correlationId } as any);
    if (!entity) {
      throw new NotFoundError(`Entity not found: ${hashId}`);
    }

    return entity as GetSaltedHashRecordOutput;
  }
}
