/**
 * ExecuteRegisterSaltedHash - Application use case
 *
 * Generated by Use Case Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: hashes
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * ExecuteRegisterSaltedHash Use Case
 *
 * DDD: Application use case for create HashRecord.
 * Orchestrates the business flow using ports (interfaces).
 */

import type { RegisterSaltedHashInput, RegisterSaltedHashOutput } from "../dto/hash-record.dto";
import type { ExecutionContextService, IdGeneratorService } from "@offhash/services/_shared/index.js";
import type { HashRecordRepository } from "../ports";
import { PermissionDeniedError, ValidationError } from "../errors";
import { CanCreate } from "../policies/can-create.policy";
export class ExecuteRegisterSaltedHash {
  constructor(
    private readonly context: ExecutionContextService,
    private readonly idGenerator: IdGeneratorService,
    private readonly hashRecord: HashRecordRepository
  ) {}

  async execute(input: RegisterSaltedHashInput): Promise<RegisterSaltedHashOutput> {
    // Generate correlation ID for this request (domain-prefixed format: {domain_prefix}_{ulid})
    const correlationId = this.idGenerator.hshId();

    // All field names extracted from OpenAPI spec: channelId, networkId, offChainStoreRef, pdRecordId, saltedHash
    // Validate input
    if (!input) {
      throw new ValidationError("Input is required");
    }
    if (!input.offChainStoreRef) {
      throw new ValidationError("offChainStoreRef is required");
    }
    if (!input.pdRecordId) {
      throw new ValidationError("pdRecordId is required");
    }
    if (!input.saltedHash) {
      throw new ValidationError("saltedHash is required");
    }    // Check policy
    if (!CanCreate.allow({} as any, "")) {
      throw new PermissionDeniedError("Operation not allowed");
    }

    // Generate entity ID in services layer using IdGeneratorService (hashes domain)
    const entityId = this.idGenerator.hshId();

    // Create entity via repository (pass ID and correlation ID for response meta)
    const entity = await this.hashRecord.registerSaltedHash({ ...input, id: entityId, createdByActorId: (input as any).createdByActorId ?? this.context.getUserId(), createdByActorType: (input as any).createdByActorType ?? "human", orgId: this.context.getOrgId(), correlationId } as any);

    return entity as RegisterSaltedHashOutput;
  }
}
