/**
 * ExecuteCreateConfigCertReview - Application use case
 *
 * Generated by Use Case Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: configcerts
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * ExecuteCreateConfigCertReview Use Case
 *
 * DDD: Application use case for create ConfigCertReview.
 * Orchestrates the business flow using ports (interfaces).
 */

import type { CreateConfigCertReviewInput, CreateConfigCertReviewOutput } from "../dto/config-cert-review.dto";
import type { ExecutionContextService, IdGeneratorService } from "@offhash/services/_shared/index.js";
import type { ConfigCertReviewRepository } from "../ports";
import { PermissionDeniedError, ValidationError } from "../errors";
import { CanCreate } from "../policies/can-create.policy";
export class ExecuteCreateConfigCertReview {
  constructor(
    private readonly context: ExecutionContextService,
    private readonly idGenerator: IdGeneratorService,
    private readonly configCertReview: ConfigCertReviewRepository
  ) {}

  async execute(input: CreateConfigCertReviewInput): Promise<CreateConfigCertReviewOutput> {
    // Generate correlation ID for this request (domain-prefixed format: {domain_prefix}_{ulid})
    const correlationId = this.idGenerator.cfgId();

    // All field names extracted from OpenAPI spec: networkId, notes, scheduledAt
    // Validate input
    if (!input) {
      throw new ValidationError("Input is required");
    }
    if (!input.networkId) {
      throw new ValidationError("networkId is required");
    }
    if (!input.scheduledAt) {
      throw new ValidationError("scheduledAt is required");
    }    // Check policy
    if (!CanCreate.allow({} as any, "")) {
      throw new PermissionDeniedError("Operation not allowed");
    }

    // Generate entity ID in services layer using IdGeneratorService (configcerts domain)
    const entityId = this.idGenerator.cfgId();

    // Create entity via repository (pass ID and correlation ID for response meta)
    const entity = await this.configCertReview.createConfigCertReview({ ...input, id: entityId, createdByActorId: (input as any).createdByActorId ?? this.context.getUserId(), createdByActorType: (input as any).createdByActorType ?? "human", orgId: this.context.getOrgId(), correlationId } as any);

    return entity as CreateConfigCertReviewOutput;
  }
}
