/**
 * ExecuteCompleteConfigCertReview - Application use case
 *
 * Generated by Use Case Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: configcerts
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * ExecuteCompleteConfigCertReview Use Case
 *
 * DDD: Application use case for create Complete.
 * Orchestrates the business flow using ports (interfaces).
 */

import type { CompleteConfigCertReviewInput, CompleteConfigCertReviewOutput } from "../dto/complete.dto";
import type { ExecutionContextService, IdGeneratorService } from "@offhash/services/_shared/index.js";
import type { CompleteRepository } from "../ports";
import { PermissionDeniedError, ValidationError } from "../errors";
import { CanCreate } from "../policies/can-create.policy";
export class ExecuteCompleteConfigCertReview {
  constructor(
    private readonly context: ExecutionContextService,
    private readonly idGenerator: IdGeneratorService,
    private readonly complete: CompleteRepository
  ) {}

  async execute(input: CompleteConfigCertReviewInput): Promise<CompleteConfigCertReviewOutput> {
    // Generate correlation ID for this request (domain-prefixed format: {domain_prefix}_{ulid})
    const correlationId = this.idGenerator.cfgId();

    // All field names extracted from OpenAPI spec: findings, notes, subjectBoundCertCount
    // Validate input
    if (!input) {
      throw new ValidationError("Input is required");
    }
    if (!input.subjectBoundCertCount) {
      throw new ValidationError("subjectBoundCertCount is required");
    }    // Check policy
    if (!CanCreate.allow({} as any, "")) {
      throw new PermissionDeniedError("Operation not allowed");
    }

    // Generate entity ID in services layer using IdGeneratorService (configcerts domain)
    const entityId = this.idGenerator.cfgId();

    // Create entity via repository (pass ID and correlation ID for response meta)
    const entity = await this.complete.completeConfigCertReview({ ...input, id: entityId, createdByActorId: (input as any).createdByActorId ?? this.context.getUserId(), createdByActorType: (input as any).createdByActorType ?? "human", orgId: this.context.getOrgId(), correlationId } as any);

    return entity as CompleteConfigCertReviewOutput;
  }
}
