/**
 * Use Case List
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: endorsement
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


/**
 * Endorsement Domain Use Cases
 * 
 * List of all use case names for the endorsement domain.
 * Used by createMockDependencies() to pre-create mocks.
 */

export const ENDORSEMENT_USE_CASES = [
  "executeGetEndorsementPeer",
  "executeListEndorsementDecisions",
  "executeListEndorsementPeers",
  "executeQuarantineEndorsementPeer"
] as const;
