/**
 * ListConfigCertReview DTO Factory
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: configcerts
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


import type { ListConfigCertReviewsParams } from "@offhash/core/configcerts";

export function createListConfigCertReviewRequest(overrides: Partial<ListConfigCertReviewsParams> = {}) {
  const raw = {
    ...overrides,
  };

  return raw;
}
