/**
 * ExecuteListPdScans - Application use case
 *
 * Generated by Use Case Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: scans
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * ExecuteListPdScans Use Case
 *
 * DDD: Application use case for list Scan.
 * Orchestrates the business flow using ports (interfaces).
 */

import type { ListPdScansInput, ListPdScansOutput } from "../dto/scan.dto";
import type { ExecutionContextService, IdGeneratorService } from "@offhash/services/_shared/index.js";
import type { ScanRepository } from "../ports";

export class ExecuteListPdScans {
  constructor(
    private readonly context: ExecutionContextService,
    private readonly idGenerator: IdGeneratorService,
    private readonly scan: ScanRepository
  ) {}

  async execute(input: ListPdScansInput): Promise<ListPdScansOutput> {
    // Generate correlation ID for this request (domain-prefixed format: {domain_prefix}_{ulid})
    const correlationId = this.idGenerator.scnId();

    // All field names extracted from OpenAPI spec: none
    // List entities via repository
    const result = await this.scan.listPdScans({ ...input, orgId: this.context.getOrgId(), correlationId } as any);

    return result as ListPdScansOutput;
  }
}
