/**
 * ExecuteScanTransactionProposal - Application use case
 *
 * Generated by Use Case Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: scans
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * ExecuteScanTransactionProposal Use Case
 *
 * DDD: Application use case for get Scan.
 * Orchestrates the business flow using ports (interfaces).
 */

import type { ScanTransactionProposalInput, ScanTransactionProposalOutput } from "../dto/scan.dto";
import type { ExecutionContextService, IdGeneratorService } from "@offhash/services/_shared/index.js";
import type { ScanRepository } from "../ports";
import { NotFoundError, ValidationError } from "../errors";

export class ExecuteScanTransactionProposal {
  constructor(
    private readonly context: ExecutionContextService,
    private readonly idGenerator: IdGeneratorService,
    private readonly scan: ScanRepository
  ) {}

  async execute(input: ScanTransactionProposalInput): Promise<ScanTransactionProposalOutput> {
    // Generate correlation ID for this request (domain-prefixed format: {domain_prefix}_{ulid})
    const correlationId = this.idGenerator.scnId();

    // All field names extracted from OpenAPI spec: channelId, fields, networkId, policyId, proposalRef
    // Validate input
    if (!input) {
      throw new ValidationError("Input is required");
    }
    if (!(input as any).channelId) {
      throw new ValidationError("channelId is required");
    }
    const channelId = (input as any).channelId;

    // Load entity via repository (pass correlation ID for response meta)
    const entity = await this.scan.scanTransactionProposal({ channelId: channelId, orgId: this.context.getOrgId(), correlationId } as any);
    if (!entity) {
      throw new NotFoundError(`Entity not found: ${channelId}`);
    }

    return entity as ScanTransactionProposalOutput;
  }
}
