/**
 * CompleteRepository Port - Application port interface
 *
 * Generated by Port Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: configcerts
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * CompleteRepository Port
 *
 * DDD: Application port for completerepository operations.
 * This is an application-level abstraction, not a domain concept.
 * Implementations live in adapters layer.
 */

import type { CompleteConfigCertReviewInput, CompleteConfigCertReviewOutput } from "../dto/complete.dto";
export interface CompleteRepository {
  completeConfigCertReview(input: CompleteConfigCertReviewInput): Promise<CompleteConfigCertReviewOutput>;
}

export type { CompleteConfigCertReviewInput, CompleteConfigCertReviewOutput } from "../dto/complete.dto";
