/**
 * ConfigCertReviewRepository Port - Application port interface
 *
 * Generated by Port Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: configcerts
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * ConfigCertReviewRepository Port
 *
 * DDD: Application port for configcertreviewrepository operations.
 * This is an application-level abstraction, not a domain concept.
 * Implementations live in adapters layer.
 */

import type { CreateConfigCertReviewInput, CreateConfigCertReviewOutput, GetConfigCertReviewInput, GetConfigCertReviewOutput, ListConfigCertReviewsInput, ListConfigCertReviewsOutput } from "../dto/config-cert-review.dto";
export interface ConfigCertReviewRepository {
  listConfigCertReviews(input: ListConfigCertReviewsInput): Promise<ListConfigCertReviewsOutput>;
  createConfigCertReview(input: CreateConfigCertReviewInput): Promise<CreateConfigCertReviewOutput>;
  getConfigCertReview(input: GetConfigCertReviewInput): Promise<GetConfigCertReviewOutput>;
}

export type { CreateConfigCertReviewInput, CreateConfigCertReviewOutput, GetConfigCertReviewInput, GetConfigCertReviewOutput, ListConfigCertReviewsInput, ListConfigCertReviewsOutput } from "../dto/config-cert-review.dto";
