/**
 * PeerRepository Port - Application port interface
 *
 * Generated by Port Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: endorsement
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * PeerRepository Port
 *
 * DDD: Application port for peerrepository operations.
 * This is an application-level abstraction, not a domain concept.
 * Implementations live in adapters layer.
 */

import type { GetEndorsementPeerInput, GetEndorsementPeerOutput, ListEndorsementPeersInput, ListEndorsementPeersOutput } from "../dto/peer.dto";
export interface PeerRepository {
  listEndorsementPeers(input: ListEndorsementPeersInput): Promise<ListEndorsementPeersOutput>;
  getEndorsementPeer(input: GetEndorsementPeerInput): Promise<GetEndorsementPeerOutput>;
}

export type { GetEndorsementPeerInput, GetEndorsementPeerOutput, ListEndorsementPeersInput, ListEndorsementPeersOutput } from "../dto/peer.dto";
