/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/v1/erasures": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List erasure jobs */
        get: operations["listErasureJobs"];
        put?: never;
        /** Execute off-chain PD erasure and orphan the linked hash */
        post: operations["executePdErasure"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/erasures/{jobId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get erasure job status and orphanization proof when available */
        get: operations["getErasureJob"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/erasure-drills": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List erasure drills */
        get: operations["listErasureDrills"];
        put?: never;
        /** Start an Article 17 erasure drill */
        post: operations["createErasureDrill"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/erasure-drills/{drillId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get erasure drill result (pass/fail) */
        get: operations["getErasureDrill"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** @description RFC 7807 Problem Details (provisional mapping for gateway errors). */
        Problem: {
            /**
             * Format: uri
             * @description URI reference identifying the problem type.
             */
            type?: string;
            /** @description Short human-readable summary. */
            title?: string;
            /** @description HTTP status code. */
            status?: number;
            /** @description Human-readable explanation specific to this occurrence. */
            detail?: string;
            /**
             * Format: uri
             * @description URI reference identifying this occurrence.
             */
            instance?: string;
            /** @description Optional machine-readable error code from the gateway. */
            code?: string;
        } & {
            [key: string]: unknown;
        };
        /**
         * @description Off-chain PD erasure job id.
         * @example ers_01HZYXK8J0M0W5N6P7Q8R9S0T1U2
         */
        ErasureJobId: string;
        /**
         * @description Salted hash record id.
         * @example hsh_01HZYXK8J0M0W5N6P7Q8R9S0T1U2
         */
        HashId: string;
        /**
         * @description Off-chain personal-data record id.
         * @example pdr_01HZYXK8J0M0W5N6P7Q8R9S0T1U2
         */
        PdRecordId: string;
        /** @enum {string} */
        ErasureJobStatus: "queued" | "running" | "done" | "failed";
        OrphanizationProof: {
            /**
             * @description Off-chain PD erasure job id.
             * @example ers_01HZYXK8J0M0W5N6P7Q8R9S0T1U2
             */
            jobId: string;
            /**
             * @description Salted hash record id.
             * @example hsh_01HZYXK8J0M0W5N6P7Q8R9S0T1U2
             */
            hashId: string;
            offChainDeleted: boolean;
            /** Format: date-time */
            orphanedAt: string;
            /** @description Integrity hash of the orphanization evidence package. */
            proofHash: string;
        };
        ErasureJob: {
            /**
             * @description Off-chain PD erasure job id.
             * @example ers_01HZYXK8J0M0W5N6P7Q8R9S0T1U2
             */
            jobId: string;
            /**
             * @description Salted hash record id.
             * @example hsh_01HZYXK8J0M0W5N6P7Q8R9S0T1U2
             */
            hashId: string;
            /**
             * @description Off-chain personal-data record id.
             * @example pdr_01HZYXK8J0M0W5N6P7Q8R9S0T1U2
             */
            pdRecordId?: string;
            erasureReason: string;
            /** @enum {string} */
            status: "queued" | "running" | "done" | "failed";
            proof?: {
                /**
                 * @description Off-chain PD erasure job id.
                 * @example ers_01HZYXK8J0M0W5N6P7Q8R9S0T1U2
                 */
                jobId: string;
                /**
                 * @description Salted hash record id.
                 * @example hsh_01HZYXK8J0M0W5N6P7Q8R9S0T1U2
                 */
                hashId: string;
                offChainDeleted: boolean;
                /** Format: date-time */
                orphanedAt: string;
                /** @description Integrity hash of the orphanization evidence package. */
                proofHash: string;
            };
            errorMessage?: string;
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            completedAt?: string;
        };
        ErasureJobListData: {
            items: {
                /**
                 * @description Off-chain PD erasure job id.
                 * @example ers_01HZYXK8J0M0W5N6P7Q8R9S0T1U2
                 */
                jobId: string;
                /**
                 * @description Salted hash record id.
                 * @example hsh_01HZYXK8J0M0W5N6P7Q8R9S0T1U2
                 */
                hashId: string;
                /**
                 * @description Off-chain personal-data record id.
                 * @example pdr_01HZYXK8J0M0W5N6P7Q8R9S0T1U2
                 */
                pdRecordId?: string;
                erasureReason: string;
                /** @enum {string} */
                status: "queued" | "running" | "done" | "failed";
                proof?: {
                    /**
                     * @description Off-chain PD erasure job id.
                     * @example ers_01HZYXK8J0M0W5N6P7Q8R9S0T1U2
                     */
                    jobId: string;
                    /**
                     * @description Salted hash record id.
                     * @example hsh_01HZYXK8J0M0W5N6P7Q8R9S0T1U2
                     */
                    hashId: string;
                    offChainDeleted: boolean;
                    /** Format: date-time */
                    orphanedAt: string;
                    /** @description Integrity hash of the orphanization evidence package. */
                    proofHash: string;
                };
                errorMessage?: string;
                /** Format: date-time */
                createdAt: string;
                /** Format: date-time */
                completedAt?: string;
            }[];
            nextCursor?: string;
        };
        ResponseMeta: {
            /**
             * Format: uuid
             * @description Correlation id for this HTTP request.
             */
            requestId?: string;
            /** @description Optional end-to-end correlation id. */
            correlationId?: string;
            /**
             * Format: date-time
             * @description Server time when the payload was produced.
             */
            generatedAt?: string;
        };
        ErasureJobListResponse: {
            data: {
                items: {
                    /**
                     * @description Off-chain PD erasure job id.
                     * @example ers_01HZYXK8J0M0W5N6P7Q8R9S0T1U2
                     */
                    jobId: string;
                    /**
                     * @description Salted hash record id.
                     * @example hsh_01HZYXK8J0M0W5N6P7Q8R9S0T1U2
                     */
                    hashId: string;
                    /**
                     * @description Off-chain personal-data record id.
                     * @example pdr_01HZYXK8J0M0W5N6P7Q8R9S0T1U2
                     */
                    pdRecordId?: string;
                    erasureReason: string;
                    /** @enum {string} */
                    status: "queued" | "running" | "done" | "failed";
                    proof?: {
                        /**
                         * @description Off-chain PD erasure job id.
                         * @example ers_01HZYXK8J0M0W5N6P7Q8R9S0T1U2
                         */
                        jobId: string;
                        /**
                         * @description Salted hash record id.
                         * @example hsh_01HZYXK8J0M0W5N6P7Q8R9S0T1U2
                         */
                        hashId: string;
                        offChainDeleted: boolean;
                        /** Format: date-time */
                        orphanedAt: string;
                        /** @description Integrity hash of the orphanization evidence package. */
                        proofHash: string;
                    };
                    errorMessage?: string;
                    /** Format: date-time */
                    createdAt: string;
                    /** Format: date-time */
                    completedAt?: string;
                }[];
                nextCursor?: string;
            };
            meta?: {
                /**
                 * Format: uuid
                 * @description Correlation id for this HTTP request.
                 */
                requestId?: string;
                /** @description Optional end-to-end correlation id. */
                correlationId?: string;
                /**
                 * Format: date-time
                 * @description Server time when the payload was produced.
                 */
                generatedAt?: string;
            };
        };
        ErasureJobCreateRequest: {
            /**
             * @description Salted hash record id.
             * @example hsh_01HZYXK8J0M0W5N6P7Q8R9S0T1U2
             */
            hashId: string;
            erasureReason: string;
            /**
             * @description Off-chain personal-data record id.
             * @example pdr_01HZYXK8J0M0W5N6P7Q8R9S0T1U2
             */
            pdRecordId?: string;
        };
        ErasureJobResponse: {
            data: {
                /**
                 * @description Off-chain PD erasure job id.
                 * @example ers_01HZYXK8J0M0W5N6P7Q8R9S0T1U2
                 */
                jobId: string;
                /**
                 * @description Salted hash record id.
                 * @example hsh_01HZYXK8J0M0W5N6P7Q8R9S0T1U2
                 */
                hashId: string;
                /**
                 * @description Off-chain personal-data record id.
                 * @example pdr_01HZYXK8J0M0W5N6P7Q8R9S0T1U2
                 */
                pdRecordId?: string;
                erasureReason: string;
                /** @enum {string} */
                status: "queued" | "running" | "done" | "failed";
                proof?: {
                    /**
                     * @description Off-chain PD erasure job id.
                     * @example ers_01HZYXK8J0M0W5N6P7Q8R9S0T1U2
                     */
                    jobId: string;
                    /**
                     * @description Salted hash record id.
                     * @example hsh_01HZYXK8J0M0W5N6P7Q8R9S0T1U2
                     */
                    hashId: string;
                    offChainDeleted: boolean;
                    /** Format: date-time */
                    orphanedAt: string;
                    /** @description Integrity hash of the orphanization evidence package. */
                    proofHash: string;
                };
                errorMessage?: string;
                /** Format: date-time */
                createdAt: string;
                /** Format: date-time */
                completedAt?: string;
            };
            meta?: {
                /**
                 * Format: uuid
                 * @description Correlation id for this HTTP request.
                 */
                requestId?: string;
                /** @description Optional end-to-end correlation id. */
                correlationId?: string;
                /**
                 * Format: date-time
                 * @description Server time when the payload was produced.
                 */
                generatedAt?: string;
            };
        };
        /**
         * @description Article 17 erasure drill id.
         * @example drl_01HZYXK8J0M0W5N6P7Q8R9S0T1U2
         */
        DrillId: string;
        /**
         * @description Fabric network identifier.
         * @example net_01HZYXK8J0M0W5N6P7Q8R9S0T1U2
         */
        NetworkId: string;
        /** @description Fabric channel identifier (opaque string). */
        ChannelId: string;
        /** @enum {string} */
        DrillResult: "pass" | "fail" | "pending";
        ErasureDrill: {
            /**
             * @description Article 17 erasure drill id.
             * @example drl_01HZYXK8J0M0W5N6P7Q8R9S0T1U2
             */
            drillId: string;
            /**
             * @description Fabric network identifier.
             * @example net_01HZYXK8J0M0W5N6P7Q8R9S0T1U2
             */
            networkId: string;
            /** @description Fabric channel identifier (opaque string). */
            channelId?: string;
            /**
             * @description Salted hash record id.
             * @example hsh_01HZYXK8J0M0W5N6P7Q8R9S0T1U2
             */
            hashId?: string;
            /**
             * @description Off-chain PD erasure job id.
             * @example ers_01HZYXK8J0M0W5N6P7Q8R9S0T1U2
             */
            jobId?: string;
            /** @enum {string} */
            result: "pass" | "fail" | "pending";
            notes?: string;
            proof?: {
                /**
                 * @description Off-chain PD erasure job id.
                 * @example ers_01HZYXK8J0M0W5N6P7Q8R9S0T1U2
                 */
                jobId: string;
                /**
                 * @description Salted hash record id.
                 * @example hsh_01HZYXK8J0M0W5N6P7Q8R9S0T1U2
                 */
                hashId: string;
                offChainDeleted: boolean;
                /** Format: date-time */
                orphanedAt: string;
                /** @description Integrity hash of the orphanization evidence package. */
                proofHash: string;
            };
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            completedAt?: string;
        };
        ErasureDrillListData: {
            items: {
                /**
                 * @description Article 17 erasure drill id.
                 * @example drl_01HZYXK8J0M0W5N6P7Q8R9S0T1U2
                 */
                drillId: string;
                /**
                 * @description Fabric network identifier.
                 * @example net_01HZYXK8J0M0W5N6P7Q8R9S0T1U2
                 */
                networkId: string;
                /** @description Fabric channel identifier (opaque string). */
                channelId?: string;
                /**
                 * @description Salted hash record id.
                 * @example hsh_01HZYXK8J0M0W5N6P7Q8R9S0T1U2
                 */
                hashId?: string;
                /**
                 * @description Off-chain PD erasure job id.
                 * @example ers_01HZYXK8J0M0W5N6P7Q8R9S0T1U2
                 */
                jobId?: string;
                /** @enum {string} */
                result: "pass" | "fail" | "pending";
                notes?: string;
                proof?: {
                    /**
                     * @description Off-chain PD erasure job id.
                     * @example ers_01HZYXK8J0M0W5N6P7Q8R9S0T1U2
                     */
                    jobId: string;
                    /**
                     * @description Salted hash record id.
                     * @example hsh_01HZYXK8J0M0W5N6P7Q8R9S0T1U2
                     */
                    hashId: string;
                    offChainDeleted: boolean;
                    /** Format: date-time */
                    orphanedAt: string;
                    /** @description Integrity hash of the orphanization evidence package. */
                    proofHash: string;
                };
                /** Format: date-time */
                createdAt: string;
                /** Format: date-time */
                completedAt?: string;
            }[];
            nextCursor?: string;
        };
        ErasureDrillListResponse: {
            data: {
                items: {
                    /**
                     * @description Article 17 erasure drill id.
                     * @example drl_01HZYXK8J0M0W5N6P7Q8R9S0T1U2
                     */
                    drillId: string;
                    /**
                     * @description Fabric network identifier.
                     * @example net_01HZYXK8J0M0W5N6P7Q8R9S0T1U2
                     */
                    networkId: string;
                    /** @description Fabric channel identifier (opaque string). */
                    channelId?: string;
                    /**
                     * @description Salted hash record id.
                     * @example hsh_01HZYXK8J0M0W5N6P7Q8R9S0T1U2
                     */
                    hashId?: string;
                    /**
                     * @description Off-chain PD erasure job id.
                     * @example ers_01HZYXK8J0M0W5N6P7Q8R9S0T1U2
                     */
                    jobId?: string;
                    /** @enum {string} */
                    result: "pass" | "fail" | "pending";
                    notes?: string;
                    proof?: {
                        /**
                         * @description Off-chain PD erasure job id.
                         * @example ers_01HZYXK8J0M0W5N6P7Q8R9S0T1U2
                         */
                        jobId: string;
                        /**
                         * @description Salted hash record id.
                         * @example hsh_01HZYXK8J0M0W5N6P7Q8R9S0T1U2
                         */
                        hashId: string;
                        offChainDeleted: boolean;
                        /** Format: date-time */
                        orphanedAt: string;
                        /** @description Integrity hash of the orphanization evidence package. */
                        proofHash: string;
                    };
                    /** Format: date-time */
                    createdAt: string;
                    /** Format: date-time */
                    completedAt?: string;
                }[];
                nextCursor?: string;
            };
            meta?: {
                /**
                 * Format: uuid
                 * @description Correlation id for this HTTP request.
                 */
                requestId?: string;
                /** @description Optional end-to-end correlation id. */
                correlationId?: string;
                /**
                 * Format: date-time
                 * @description Server time when the payload was produced.
                 */
                generatedAt?: string;
            };
        };
        ErasureDrillCreateRequest: {
            /**
             * @description Fabric network identifier.
             * @example net_01HZYXK8J0M0W5N6P7Q8R9S0T1U2
             */
            networkId: string;
            /** @description Fabric channel identifier (opaque string). */
            channelId?: string;
            /**
             * @description Optional specific hash to drill; otherwise platform picks a fixture.
             * @example hsh_01HZYXK8J0M0W5N6P7Q8R9S0T1U2
             */
            hashId?: string;
            notes?: string;
        };
        ErasureDrillResponse: {
            data: {
                /**
                 * @description Article 17 erasure drill id.
                 * @example drl_01HZYXK8J0M0W5N6P7Q8R9S0T1U2
                 */
                drillId: string;
                /**
                 * @description Fabric network identifier.
                 * @example net_01HZYXK8J0M0W5N6P7Q8R9S0T1U2
                 */
                networkId: string;
                /** @description Fabric channel identifier (opaque string). */
                channelId?: string;
                /**
                 * @description Salted hash record id.
                 * @example hsh_01HZYXK8J0M0W5N6P7Q8R9S0T1U2
                 */
                hashId?: string;
                /**
                 * @description Off-chain PD erasure job id.
                 * @example ers_01HZYXK8J0M0W5N6P7Q8R9S0T1U2
                 */
                jobId?: string;
                /** @enum {string} */
                result: "pass" | "fail" | "pending";
                notes?: string;
                proof?: {
                    /**
                     * @description Off-chain PD erasure job id.
                     * @example ers_01HZYXK8J0M0W5N6P7Q8R9S0T1U2
                     */
                    jobId: string;
                    /**
                     * @description Salted hash record id.
                     * @example hsh_01HZYXK8J0M0W5N6P7Q8R9S0T1U2
                     */
                    hashId: string;
                    offChainDeleted: boolean;
                    /** Format: date-time */
                    orphanedAt: string;
                    /** @description Integrity hash of the orphanization evidence package. */
                    proofHash: string;
                };
                /** Format: date-time */
                createdAt: string;
                /** Format: date-time */
                completedAt?: string;
            };
            meta?: {
                /**
                 * Format: uuid
                 * @description Correlation id for this HTTP request.
                 */
                requestId?: string;
                /** @description Optional end-to-end correlation id. */
                correlationId?: string;
                /**
                 * Format: date-time
                 * @description Server time when the payload was produced.
                 */
                generatedAt?: string;
            };
        };
    };
    responses: {
        /** @description Error (RFC 7807 Problem Details) */
        Problem: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": {
                    /**
                     * Format: uri
                     * @description URI reference identifying the problem type.
                     */
                    type?: string;
                    /** @description Short human-readable summary. */
                    title?: string;
                    /** @description HTTP status code. */
                    status?: number;
                    /** @description Human-readable explanation specific to this occurrence. */
                    detail?: string;
                    /**
                     * Format: uri
                     * @description URI reference identifying this occurrence.
                     */
                    instance?: string;
                    /** @description Optional machine-readable error code from the gateway. */
                    code?: string;
                } & {
                    [key: string]: unknown;
                };
                "application/json": {
                    /**
                     * Format: uri
                     * @description URI reference identifying the problem type.
                     */
                    type?: string;
                    /** @description Short human-readable summary. */
                    title?: string;
                    /** @description HTTP status code. */
                    status?: number;
                    /** @description Human-readable explanation specific to this occurrence. */
                    detail?: string;
                    /**
                     * Format: uri
                     * @description URI reference identifying this occurrence.
                     */
                    instance?: string;
                    /** @description Optional machine-readable error code from the gateway. */
                    code?: string;
                } & {
                    [key: string]: unknown;
                };
            };
        };
        /** @description Missing or invalid API key */
        Unauthorized: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": {
                    /**
                     * Format: uri
                     * @description URI reference identifying the problem type.
                     */
                    type?: string;
                    /** @description Short human-readable summary. */
                    title?: string;
                    /** @description HTTP status code. */
                    status?: number;
                    /** @description Human-readable explanation specific to this occurrence. */
                    detail?: string;
                    /**
                     * Format: uri
                     * @description URI reference identifying this occurrence.
                     */
                    instance?: string;
                    /** @description Optional machine-readable error code from the gateway. */
                    code?: string;
                } & {
                    [key: string]: unknown;
                };
                "application/json": {
                    /**
                     * Format: uri
                     * @description URI reference identifying the problem type.
                     */
                    type?: string;
                    /** @description Short human-readable summary. */
                    title?: string;
                    /** @description HTTP status code. */
                    status?: number;
                    /** @description Human-readable explanation specific to this occurrence. */
                    detail?: string;
                    /**
                     * Format: uri
                     * @description URI reference identifying this occurrence.
                     */
                    instance?: string;
                    /** @description Optional machine-readable error code from the gateway. */
                    code?: string;
                } & {
                    [key: string]: unknown;
                };
            };
        };
        /** @description Malformed request */
        BadRequest: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": {
                    /**
                     * Format: uri
                     * @description URI reference identifying the problem type.
                     */
                    type?: string;
                    /** @description Short human-readable summary. */
                    title?: string;
                    /** @description HTTP status code. */
                    status?: number;
                    /** @description Human-readable explanation specific to this occurrence. */
                    detail?: string;
                    /**
                     * Format: uri
                     * @description URI reference identifying this occurrence.
                     */
                    instance?: string;
                    /** @description Optional machine-readable error code from the gateway. */
                    code?: string;
                } & {
                    [key: string]: unknown;
                };
                "application/json": {
                    /**
                     * Format: uri
                     * @description URI reference identifying the problem type.
                     */
                    type?: string;
                    /** @description Short human-readable summary. */
                    title?: string;
                    /** @description HTTP status code. */
                    status?: number;
                    /** @description Human-readable explanation specific to this occurrence. */
                    detail?: string;
                    /**
                     * Format: uri
                     * @description URI reference identifying this occurrence.
                     */
                    instance?: string;
                    /** @description Optional machine-readable error code from the gateway. */
                    code?: string;
                } & {
                    [key: string]: unknown;
                };
            };
        };
        /** @description Resource not found */
        NotFound: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": {
                    /**
                     * Format: uri
                     * @description URI reference identifying the problem type.
                     */
                    type?: string;
                    /** @description Short human-readable summary. */
                    title?: string;
                    /** @description HTTP status code. */
                    status?: number;
                    /** @description Human-readable explanation specific to this occurrence. */
                    detail?: string;
                    /**
                     * Format: uri
                     * @description URI reference identifying this occurrence.
                     */
                    instance?: string;
                    /** @description Optional machine-readable error code from the gateway. */
                    code?: string;
                } & {
                    [key: string]: unknown;
                };
                "application/json": {
                    /**
                     * Format: uri
                     * @description URI reference identifying the problem type.
                     */
                    type?: string;
                    /** @description Short human-readable summary. */
                    title?: string;
                    /** @description HTTP status code. */
                    status?: number;
                    /** @description Human-readable explanation specific to this occurrence. */
                    detail?: string;
                    /**
                     * Format: uri
                     * @description URI reference identifying this occurrence.
                     */
                    instance?: string;
                    /** @description Optional machine-readable error code from the gateway. */
                    code?: string;
                } & {
                    [key: string]: unknown;
                };
            };
        };
    };
    parameters: {
        /** @description Opaque keyset cursor from a previous page. */
        Cursor: string;
        /** @description Page size (default 50, max 200). */
        Limit: number;
        /**
         * @description Client-supplied key for safe retries on mutating POSTs (≤128 chars).
         *     Replay with the same key and body returns the original result; different
         *     body with the same key yields 409.
         */
        IdempotencyKey: string;
        /** @description Erasure job id (`ers_…`). */
        ErasureJobIdPath: string;
        /** @description Erasure drill id (`drl_…`). */
        DrillIdPath: string;
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    listErasureJobs: {
        parameters: {
            query?: {
                /** @description Opaque keyset cursor from a previous page. */
                cursor?: string;
                /** @description Page size (default 50, max 200). */
                limit?: number;
                status?: "queued" | "running" | "done" | "failed";
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Erasure jobs page */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: {
                            items: {
                                /**
                                 * @description Off-chain PD erasure job id.
                                 * @example ers_01HZYXK8J0M0W5N6P7Q8R9S0T1U2
                                 */
                                jobId: string;
                                /**
                                 * @description Salted hash record id.
                                 * @example hsh_01HZYXK8J0M0W5N6P7Q8R9S0T1U2
                                 */
                                hashId: string;
                                /**
                                 * @description Off-chain personal-data record id.
                                 * @example pdr_01HZYXK8J0M0W5N6P7Q8R9S0T1U2
                                 */
                                pdRecordId?: string;
                                erasureReason: string;
                                /** @enum {string} */
                                status: "queued" | "running" | "done" | "failed";
                                proof?: {
                                    /**
                                     * @description Off-chain PD erasure job id.
                                     * @example ers_01HZYXK8J0M0W5N6P7Q8R9S0T1U2
                                     */
                                    jobId: string;
                                    /**
                                     * @description Salted hash record id.
                                     * @example hsh_01HZYXK8J0M0W5N6P7Q8R9S0T1U2
                                     */
                                    hashId: string;
                                    offChainDeleted: boolean;
                                    /** Format: date-time */
                                    orphanedAt: string;
                                    /** @description Integrity hash of the orphanization evidence package. */
                                    proofHash: string;
                                };
                                errorMessage?: string;
                                /** Format: date-time */
                                createdAt: string;
                                /** Format: date-time */
                                completedAt?: string;
                            }[];
                            nextCursor?: string;
                        };
                        meta?: {
                            /**
                             * Format: uuid
                             * @description Correlation id for this HTTP request.
                             */
                            requestId?: string;
                            /** @description Optional end-to-end correlation id. */
                            correlationId?: string;
                            /**
                             * Format: date-time
                             * @description Server time when the payload was produced.
                             */
                            generatedAt?: string;
                        };
                    };
                };
            };
            /** @description Missing or invalid API key */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": {
                        /**
                         * Format: uri
                         * @description URI reference identifying the problem type.
                         */
                        type?: string;
                        /** @description Short human-readable summary. */
                        title?: string;
                        /** @description HTTP status code. */
                        status?: number;
                        /** @description Human-readable explanation specific to this occurrence. */
                        detail?: string;
                        /**
                         * Format: uri
                         * @description URI reference identifying this occurrence.
                         */
                        instance?: string;
                        /** @description Optional machine-readable error code from the gateway. */
                        code?: string;
                    } & {
                        [key: string]: unknown;
                    };
                    "application/json": {
                        /**
                         * Format: uri
                         * @description URI reference identifying the problem type.
                         */
                        type?: string;
                        /** @description Short human-readable summary. */
                        title?: string;
                        /** @description HTTP status code. */
                        status?: number;
                        /** @description Human-readable explanation specific to this occurrence. */
                        detail?: string;
                        /**
                         * Format: uri
                         * @description URI reference identifying this occurrence.
                         */
                        instance?: string;
                        /** @description Optional machine-readable error code from the gateway. */
                        code?: string;
                    } & {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Error (RFC 7807 Problem Details) */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": {
                        /**
                         * Format: uri
                         * @description URI reference identifying the problem type.
                         */
                        type?: string;
                        /** @description Short human-readable summary. */
                        title?: string;
                        /** @description HTTP status code. */
                        status?: number;
                        /** @description Human-readable explanation specific to this occurrence. */
                        detail?: string;
                        /**
                         * Format: uri
                         * @description URI reference identifying this occurrence.
                         */
                        instance?: string;
                        /** @description Optional machine-readable error code from the gateway. */
                        code?: string;
                    } & {
                        [key: string]: unknown;
                    };
                    "application/json": {
                        /**
                         * Format: uri
                         * @description URI reference identifying the problem type.
                         */
                        type?: string;
                        /** @description Short human-readable summary. */
                        title?: string;
                        /** @description HTTP status code. */
                        status?: number;
                        /** @description Human-readable explanation specific to this occurrence. */
                        detail?: string;
                        /**
                         * Format: uri
                         * @description URI reference identifying this occurrence.
                         */
                        instance?: string;
                        /** @description Optional machine-readable error code from the gateway. */
                        code?: string;
                    } & {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    executePdErasure: {
        parameters: {
            query?: never;
            header: {
                /**
                 * @description Client-supplied key for safe retries on mutating POSTs (≤128 chars).
                 *     Replay with the same key and body returns the original result; different
                 *     body with the same key yields 409.
                 */
                "Idempotency-Key": string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    /**
                     * @description Salted hash record id.
                     * @example hsh_01HZYXK8J0M0W5N6P7Q8R9S0T1U2
                     */
                    hashId: string;
                    erasureReason: string;
                    /**
                     * @description Off-chain personal-data record id.
                     * @example pdr_01HZYXK8J0M0W5N6P7Q8R9S0T1U2
                     */
                    pdRecordId?: string;
                };
            };
        };
        responses: {
            /** @description Erasure job accepted */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: {
                            /**
                             * @description Off-chain PD erasure job id.
                             * @example ers_01HZYXK8J0M0W5N6P7Q8R9S0T1U2
                             */
                            jobId: string;
                            /**
                             * @description Salted hash record id.
                             * @example hsh_01HZYXK8J0M0W5N6P7Q8R9S0T1U2
                             */
                            hashId: string;
                            /**
                             * @description Off-chain personal-data record id.
                             * @example pdr_01HZYXK8J0M0W5N6P7Q8R9S0T1U2
                             */
                            pdRecordId?: string;
                            erasureReason: string;
                            /** @enum {string} */
                            status: "queued" | "running" | "done" | "failed";
                            proof?: {
                                /**
                                 * @description Off-chain PD erasure job id.
                                 * @example ers_01HZYXK8J0M0W5N6P7Q8R9S0T1U2
                                 */
                                jobId: string;
                                /**
                                 * @description Salted hash record id.
                                 * @example hsh_01HZYXK8J0M0W5N6P7Q8R9S0T1U2
                                 */
                                hashId: string;
                                offChainDeleted: boolean;
                                /** Format: date-time */
                                orphanedAt: string;
                                /** @description Integrity hash of the orphanization evidence package. */
                                proofHash: string;
                            };
                            errorMessage?: string;
                            /** Format: date-time */
                            createdAt: string;
                            /** Format: date-time */
                            completedAt?: string;
                        };
                        meta?: {
                            /**
                             * Format: uuid
                             * @description Correlation id for this HTTP request.
                             */
                            requestId?: string;
                            /** @description Optional end-to-end correlation id. */
                            correlationId?: string;
                            /**
                             * Format: date-time
                             * @description Server time when the payload was produced.
                             */
                            generatedAt?: string;
                        };
                    };
                };
            };
            /** @description Malformed request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": {
                        /**
                         * Format: uri
                         * @description URI reference identifying the problem type.
                         */
                        type?: string;
                        /** @description Short human-readable summary. */
                        title?: string;
                        /** @description HTTP status code. */
                        status?: number;
                        /** @description Human-readable explanation specific to this occurrence. */
                        detail?: string;
                        /**
                         * Format: uri
                         * @description URI reference identifying this occurrence.
                         */
                        instance?: string;
                        /** @description Optional machine-readable error code from the gateway. */
                        code?: string;
                    } & {
                        [key: string]: unknown;
                    };
                    "application/json": {
                        /**
                         * Format: uri
                         * @description URI reference identifying the problem type.
                         */
                        type?: string;
                        /** @description Short human-readable summary. */
                        title?: string;
                        /** @description HTTP status code. */
                        status?: number;
                        /** @description Human-readable explanation specific to this occurrence. */
                        detail?: string;
                        /**
                         * Format: uri
                         * @description URI reference identifying this occurrence.
                         */
                        instance?: string;
                        /** @description Optional machine-readable error code from the gateway. */
                        code?: string;
                    } & {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Missing or invalid API key */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": {
                        /**
                         * Format: uri
                         * @description URI reference identifying the problem type.
                         */
                        type?: string;
                        /** @description Short human-readable summary. */
                        title?: string;
                        /** @description HTTP status code. */
                        status?: number;
                        /** @description Human-readable explanation specific to this occurrence. */
                        detail?: string;
                        /**
                         * Format: uri
                         * @description URI reference identifying this occurrence.
                         */
                        instance?: string;
                        /** @description Optional machine-readable error code from the gateway. */
                        code?: string;
                    } & {
                        [key: string]: unknown;
                    };
                    "application/json": {
                        /**
                         * Format: uri
                         * @description URI reference identifying the problem type.
                         */
                        type?: string;
                        /** @description Short human-readable summary. */
                        title?: string;
                        /** @description HTTP status code. */
                        status?: number;
                        /** @description Human-readable explanation specific to this occurrence. */
                        detail?: string;
                        /**
                         * Format: uri
                         * @description URI reference identifying this occurrence.
                         */
                        instance?: string;
                        /** @description Optional machine-readable error code from the gateway. */
                        code?: string;
                    } & {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Error (RFC 7807 Problem Details) */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": {
                        /**
                         * Format: uri
                         * @description URI reference identifying the problem type.
                         */
                        type?: string;
                        /** @description Short human-readable summary. */
                        title?: string;
                        /** @description HTTP status code. */
                        status?: number;
                        /** @description Human-readable explanation specific to this occurrence. */
                        detail?: string;
                        /**
                         * Format: uri
                         * @description URI reference identifying this occurrence.
                         */
                        instance?: string;
                        /** @description Optional machine-readable error code from the gateway. */
                        code?: string;
                    } & {
                        [key: string]: unknown;
                    };
                    "application/json": {
                        /**
                         * Format: uri
                         * @description URI reference identifying the problem type.
                         */
                        type?: string;
                        /** @description Short human-readable summary. */
                        title?: string;
                        /** @description HTTP status code. */
                        status?: number;
                        /** @description Human-readable explanation specific to this occurrence. */
                        detail?: string;
                        /**
                         * Format: uri
                         * @description URI reference identifying this occurrence.
                         */
                        instance?: string;
                        /** @description Optional machine-readable error code from the gateway. */
                        code?: string;
                    } & {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    getErasureJob: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Erasure job id (`ers_…`). */
                jobId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Erasure job */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: {
                            /**
                             * @description Off-chain PD erasure job id.
                             * @example ers_01HZYXK8J0M0W5N6P7Q8R9S0T1U2
                             */
                            jobId: string;
                            /**
                             * @description Salted hash record id.
                             * @example hsh_01HZYXK8J0M0W5N6P7Q8R9S0T1U2
                             */
                            hashId: string;
                            /**
                             * @description Off-chain personal-data record id.
                             * @example pdr_01HZYXK8J0M0W5N6P7Q8R9S0T1U2
                             */
                            pdRecordId?: string;
                            erasureReason: string;
                            /** @enum {string} */
                            status: "queued" | "running" | "done" | "failed";
                            proof?: {
                                /**
                                 * @description Off-chain PD erasure job id.
                                 * @example ers_01HZYXK8J0M0W5N6P7Q8R9S0T1U2
                                 */
                                jobId: string;
                                /**
                                 * @description Salted hash record id.
                                 * @example hsh_01HZYXK8J0M0W5N6P7Q8R9S0T1U2
                                 */
                                hashId: string;
                                offChainDeleted: boolean;
                                /** Format: date-time */
                                orphanedAt: string;
                                /** @description Integrity hash of the orphanization evidence package. */
                                proofHash: string;
                            };
                            errorMessage?: string;
                            /** Format: date-time */
                            createdAt: string;
                            /** Format: date-time */
                            completedAt?: string;
                        };
                        meta?: {
                            /**
                             * Format: uuid
                             * @description Correlation id for this HTTP request.
                             */
                            requestId?: string;
                            /** @description Optional end-to-end correlation id. */
                            correlationId?: string;
                            /**
                             * Format: date-time
                             * @description Server time when the payload was produced.
                             */
                            generatedAt?: string;
                        };
                    };
                };
            };
            /** @description Missing or invalid API key */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": {
                        /**
                         * Format: uri
                         * @description URI reference identifying the problem type.
                         */
                        type?: string;
                        /** @description Short human-readable summary. */
                        title?: string;
                        /** @description HTTP status code. */
                        status?: number;
                        /** @description Human-readable explanation specific to this occurrence. */
                        detail?: string;
                        /**
                         * Format: uri
                         * @description URI reference identifying this occurrence.
                         */
                        instance?: string;
                        /** @description Optional machine-readable error code from the gateway. */
                        code?: string;
                    } & {
                        [key: string]: unknown;
                    };
                    "application/json": {
                        /**
                         * Format: uri
                         * @description URI reference identifying the problem type.
                         */
                        type?: string;
                        /** @description Short human-readable summary. */
                        title?: string;
                        /** @description HTTP status code. */
                        status?: number;
                        /** @description Human-readable explanation specific to this occurrence. */
                        detail?: string;
                        /**
                         * Format: uri
                         * @description URI reference identifying this occurrence.
                         */
                        instance?: string;
                        /** @description Optional machine-readable error code from the gateway. */
                        code?: string;
                    } & {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Resource not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": {
                        /**
                         * Format: uri
                         * @description URI reference identifying the problem type.
                         */
                        type?: string;
                        /** @description Short human-readable summary. */
                        title?: string;
                        /** @description HTTP status code. */
                        status?: number;
                        /** @description Human-readable explanation specific to this occurrence. */
                        detail?: string;
                        /**
                         * Format: uri
                         * @description URI reference identifying this occurrence.
                         */
                        instance?: string;
                        /** @description Optional machine-readable error code from the gateway. */
                        code?: string;
                    } & {
                        [key: string]: unknown;
                    };
                    "application/json": {
                        /**
                         * Format: uri
                         * @description URI reference identifying the problem type.
                         */
                        type?: string;
                        /** @description Short human-readable summary. */
                        title?: string;
                        /** @description HTTP status code. */
                        status?: number;
                        /** @description Human-readable explanation specific to this occurrence. */
                        detail?: string;
                        /**
                         * Format: uri
                         * @description URI reference identifying this occurrence.
                         */
                        instance?: string;
                        /** @description Optional machine-readable error code from the gateway. */
                        code?: string;
                    } & {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Error (RFC 7807 Problem Details) */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": {
                        /**
                         * Format: uri
                         * @description URI reference identifying the problem type.
                         */
                        type?: string;
                        /** @description Short human-readable summary. */
                        title?: string;
                        /** @description HTTP status code. */
                        status?: number;
                        /** @description Human-readable explanation specific to this occurrence. */
                        detail?: string;
                        /**
                         * Format: uri
                         * @description URI reference identifying this occurrence.
                         */
                        instance?: string;
                        /** @description Optional machine-readable error code from the gateway. */
                        code?: string;
                    } & {
                        [key: string]: unknown;
                    };
                    "application/json": {
                        /**
                         * Format: uri
                         * @description URI reference identifying the problem type.
                         */
                        type?: string;
                        /** @description Short human-readable summary. */
                        title?: string;
                        /** @description HTTP status code. */
                        status?: number;
                        /** @description Human-readable explanation specific to this occurrence. */
                        detail?: string;
                        /**
                         * Format: uri
                         * @description URI reference identifying this occurrence.
                         */
                        instance?: string;
                        /** @description Optional machine-readable error code from the gateway. */
                        code?: string;
                    } & {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    listErasureDrills: {
        parameters: {
            query?: {
                /** @description Opaque keyset cursor from a previous page. */
                cursor?: string;
                /** @description Page size (default 50, max 200). */
                limit?: number;
                result?: "pass" | "fail" | "pending";
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Drills page */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: {
                            items: {
                                /**
                                 * @description Article 17 erasure drill id.
                                 * @example drl_01HZYXK8J0M0W5N6P7Q8R9S0T1U2
                                 */
                                drillId: string;
                                /**
                                 * @description Fabric network identifier.
                                 * @example net_01HZYXK8J0M0W5N6P7Q8R9S0T1U2
                                 */
                                networkId: string;
                                /** @description Fabric channel identifier (opaque string). */
                                channelId?: string;
                                /**
                                 * @description Salted hash record id.
                                 * @example hsh_01HZYXK8J0M0W5N6P7Q8R9S0T1U2
                                 */
                                hashId?: string;
                                /**
                                 * @description Off-chain PD erasure job id.
                                 * @example ers_01HZYXK8J0M0W5N6P7Q8R9S0T1U2
                                 */
                                jobId?: string;
                                /** @enum {string} */
                                result: "pass" | "fail" | "pending";
                                notes?: string;
                                proof?: {
                                    /**
                                     * @description Off-chain PD erasure job id.
                                     * @example ers_01HZYXK8J0M0W5N6P7Q8R9S0T1U2
                                     */
                                    jobId: string;
                                    /**
                                     * @description Salted hash record id.
                                     * @example hsh_01HZYXK8J0M0W5N6P7Q8R9S0T1U2
                                     */
                                    hashId: string;
                                    offChainDeleted: boolean;
                                    /** Format: date-time */
                                    orphanedAt: string;
                                    /** @description Integrity hash of the orphanization evidence package. */
                                    proofHash: string;
                                };
                                /** Format: date-time */
                                createdAt: string;
                                /** Format: date-time */
                                completedAt?: string;
                            }[];
                            nextCursor?: string;
                        };
                        meta?: {
                            /**
                             * Format: uuid
                             * @description Correlation id for this HTTP request.
                             */
                            requestId?: string;
                            /** @description Optional end-to-end correlation id. */
                            correlationId?: string;
                            /**
                             * Format: date-time
                             * @description Server time when the payload was produced.
                             */
                            generatedAt?: string;
                        };
                    };
                };
            };
            /** @description Missing or invalid API key */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": {
                        /**
                         * Format: uri
                         * @description URI reference identifying the problem type.
                         */
                        type?: string;
                        /** @description Short human-readable summary. */
                        title?: string;
                        /** @description HTTP status code. */
                        status?: number;
                        /** @description Human-readable explanation specific to this occurrence. */
                        detail?: string;
                        /**
                         * Format: uri
                         * @description URI reference identifying this occurrence.
                         */
                        instance?: string;
                        /** @description Optional machine-readable error code from the gateway. */
                        code?: string;
                    } & {
                        [key: string]: unknown;
                    };
                    "application/json": {
                        /**
                         * Format: uri
                         * @description URI reference identifying the problem type.
                         */
                        type?: string;
                        /** @description Short human-readable summary. */
                        title?: string;
                        /** @description HTTP status code. */
                        status?: number;
                        /** @description Human-readable explanation specific to this occurrence. */
                        detail?: string;
                        /**
                         * Format: uri
                         * @description URI reference identifying this occurrence.
                         */
                        instance?: string;
                        /** @description Optional machine-readable error code from the gateway. */
                        code?: string;
                    } & {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Error (RFC 7807 Problem Details) */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": {
                        /**
                         * Format: uri
                         * @description URI reference identifying the problem type.
                         */
                        type?: string;
                        /** @description Short human-readable summary. */
                        title?: string;
                        /** @description HTTP status code. */
                        status?: number;
                        /** @description Human-readable explanation specific to this occurrence. */
                        detail?: string;
                        /**
                         * Format: uri
                         * @description URI reference identifying this occurrence.
                         */
                        instance?: string;
                        /** @description Optional machine-readable error code from the gateway. */
                        code?: string;
                    } & {
                        [key: string]: unknown;
                    };
                    "application/json": {
                        /**
                         * Format: uri
                         * @description URI reference identifying the problem type.
                         */
                        type?: string;
                        /** @description Short human-readable summary. */
                        title?: string;
                        /** @description HTTP status code. */
                        status?: number;
                        /** @description Human-readable explanation specific to this occurrence. */
                        detail?: string;
                        /**
                         * Format: uri
                         * @description URI reference identifying this occurrence.
                         */
                        instance?: string;
                        /** @description Optional machine-readable error code from the gateway. */
                        code?: string;
                    } & {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    createErasureDrill: {
        parameters: {
            query?: never;
            header: {
                /**
                 * @description Client-supplied key for safe retries on mutating POSTs (≤128 chars).
                 *     Replay with the same key and body returns the original result; different
                 *     body with the same key yields 409.
                 */
                "Idempotency-Key": string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    /**
                     * @description Fabric network identifier.
                     * @example net_01HZYXK8J0M0W5N6P7Q8R9S0T1U2
                     */
                    networkId: string;
                    /** @description Fabric channel identifier (opaque string). */
                    channelId?: string;
                    /**
                     * @description Optional specific hash to drill; otherwise platform picks a fixture.
                     * @example hsh_01HZYXK8J0M0W5N6P7Q8R9S0T1U2
                     */
                    hashId?: string;
                    notes?: string;
                };
            };
        };
        responses: {
            /** @description Drill created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: {
                            /**
                             * @description Article 17 erasure drill id.
                             * @example drl_01HZYXK8J0M0W5N6P7Q8R9S0T1U2
                             */
                            drillId: string;
                            /**
                             * @description Fabric network identifier.
                             * @example net_01HZYXK8J0M0W5N6P7Q8R9S0T1U2
                             */
                            networkId: string;
                            /** @description Fabric channel identifier (opaque string). */
                            channelId?: string;
                            /**
                             * @description Salted hash record id.
                             * @example hsh_01HZYXK8J0M0W5N6P7Q8R9S0T1U2
                             */
                            hashId?: string;
                            /**
                             * @description Off-chain PD erasure job id.
                             * @example ers_01HZYXK8J0M0W5N6P7Q8R9S0T1U2
                             */
                            jobId?: string;
                            /** @enum {string} */
                            result: "pass" | "fail" | "pending";
                            notes?: string;
                            proof?: {
                                /**
                                 * @description Off-chain PD erasure job id.
                                 * @example ers_01HZYXK8J0M0W5N6P7Q8R9S0T1U2
                                 */
                                jobId: string;
                                /**
                                 * @description Salted hash record id.
                                 * @example hsh_01HZYXK8J0M0W5N6P7Q8R9S0T1U2
                                 */
                                hashId: string;
                                offChainDeleted: boolean;
                                /** Format: date-time */
                                orphanedAt: string;
                                /** @description Integrity hash of the orphanization evidence package. */
                                proofHash: string;
                            };
                            /** Format: date-time */
                            createdAt: string;
                            /** Format: date-time */
                            completedAt?: string;
                        };
                        meta?: {
                            /**
                             * Format: uuid
                             * @description Correlation id for this HTTP request.
                             */
                            requestId?: string;
                            /** @description Optional end-to-end correlation id. */
                            correlationId?: string;
                            /**
                             * Format: date-time
                             * @description Server time when the payload was produced.
                             */
                            generatedAt?: string;
                        };
                    };
                };
            };
            /** @description Malformed request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": {
                        /**
                         * Format: uri
                         * @description URI reference identifying the problem type.
                         */
                        type?: string;
                        /** @description Short human-readable summary. */
                        title?: string;
                        /** @description HTTP status code. */
                        status?: number;
                        /** @description Human-readable explanation specific to this occurrence. */
                        detail?: string;
                        /**
                         * Format: uri
                         * @description URI reference identifying this occurrence.
                         */
                        instance?: string;
                        /** @description Optional machine-readable error code from the gateway. */
                        code?: string;
                    } & {
                        [key: string]: unknown;
                    };
                    "application/json": {
                        /**
                         * Format: uri
                         * @description URI reference identifying the problem type.
                         */
                        type?: string;
                        /** @description Short human-readable summary. */
                        title?: string;
                        /** @description HTTP status code. */
                        status?: number;
                        /** @description Human-readable explanation specific to this occurrence. */
                        detail?: string;
                        /**
                         * Format: uri
                         * @description URI reference identifying this occurrence.
                         */
                        instance?: string;
                        /** @description Optional machine-readable error code from the gateway. */
                        code?: string;
                    } & {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Missing or invalid API key */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": {
                        /**
                         * Format: uri
                         * @description URI reference identifying the problem type.
                         */
                        type?: string;
                        /** @description Short human-readable summary. */
                        title?: string;
                        /** @description HTTP status code. */
                        status?: number;
                        /** @description Human-readable explanation specific to this occurrence. */
                        detail?: string;
                        /**
                         * Format: uri
                         * @description URI reference identifying this occurrence.
                         */
                        instance?: string;
                        /** @description Optional machine-readable error code from the gateway. */
                        code?: string;
                    } & {
                        [key: string]: unknown;
                    };
                    "application/json": {
                        /**
                         * Format: uri
                         * @description URI reference identifying the problem type.
                         */
                        type?: string;
                        /** @description Short human-readable summary. */
                        title?: string;
                        /** @description HTTP status code. */
                        status?: number;
                        /** @description Human-readable explanation specific to this occurrence. */
                        detail?: string;
                        /**
                         * Format: uri
                         * @description URI reference identifying this occurrence.
                         */
                        instance?: string;
                        /** @description Optional machine-readable error code from the gateway. */
                        code?: string;
                    } & {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Error (RFC 7807 Problem Details) */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": {
                        /**
                         * Format: uri
                         * @description URI reference identifying the problem type.
                         */
                        type?: string;
                        /** @description Short human-readable summary. */
                        title?: string;
                        /** @description HTTP status code. */
                        status?: number;
                        /** @description Human-readable explanation specific to this occurrence. */
                        detail?: string;
                        /**
                         * Format: uri
                         * @description URI reference identifying this occurrence.
                         */
                        instance?: string;
                        /** @description Optional machine-readable error code from the gateway. */
                        code?: string;
                    } & {
                        [key: string]: unknown;
                    };
                    "application/json": {
                        /**
                         * Format: uri
                         * @description URI reference identifying the problem type.
                         */
                        type?: string;
                        /** @description Short human-readable summary. */
                        title?: string;
                        /** @description HTTP status code. */
                        status?: number;
                        /** @description Human-readable explanation specific to this occurrence. */
                        detail?: string;
                        /**
                         * Format: uri
                         * @description URI reference identifying this occurrence.
                         */
                        instance?: string;
                        /** @description Optional machine-readable error code from the gateway. */
                        code?: string;
                    } & {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    getErasureDrill: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Erasure drill id (`drl_…`). */
                drillId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Drill */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: {
                            /**
                             * @description Article 17 erasure drill id.
                             * @example drl_01HZYXK8J0M0W5N6P7Q8R9S0T1U2
                             */
                            drillId: string;
                            /**
                             * @description Fabric network identifier.
                             * @example net_01HZYXK8J0M0W5N6P7Q8R9S0T1U2
                             */
                            networkId: string;
                            /** @description Fabric channel identifier (opaque string). */
                            channelId?: string;
                            /**
                             * @description Salted hash record id.
                             * @example hsh_01HZYXK8J0M0W5N6P7Q8R9S0T1U2
                             */
                            hashId?: string;
                            /**
                             * @description Off-chain PD erasure job id.
                             * @example ers_01HZYXK8J0M0W5N6P7Q8R9S0T1U2
                             */
                            jobId?: string;
                            /** @enum {string} */
                            result: "pass" | "fail" | "pending";
                            notes?: string;
                            proof?: {
                                /**
                                 * @description Off-chain PD erasure job id.
                                 * @example ers_01HZYXK8J0M0W5N6P7Q8R9S0T1U2
                                 */
                                jobId: string;
                                /**
                                 * @description Salted hash record id.
                                 * @example hsh_01HZYXK8J0M0W5N6P7Q8R9S0T1U2
                                 */
                                hashId: string;
                                offChainDeleted: boolean;
                                /** Format: date-time */
                                orphanedAt: string;
                                /** @description Integrity hash of the orphanization evidence package. */
                                proofHash: string;
                            };
                            /** Format: date-time */
                            createdAt: string;
                            /** Format: date-time */
                            completedAt?: string;
                        };
                        meta?: {
                            /**
                             * Format: uuid
                             * @description Correlation id for this HTTP request.
                             */
                            requestId?: string;
                            /** @description Optional end-to-end correlation id. */
                            correlationId?: string;
                            /**
                             * Format: date-time
                             * @description Server time when the payload was produced.
                             */
                            generatedAt?: string;
                        };
                    };
                };
            };
            /** @description Missing or invalid API key */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": {
                        /**
                         * Format: uri
                         * @description URI reference identifying the problem type.
                         */
                        type?: string;
                        /** @description Short human-readable summary. */
                        title?: string;
                        /** @description HTTP status code. */
                        status?: number;
                        /** @description Human-readable explanation specific to this occurrence. */
                        detail?: string;
                        /**
                         * Format: uri
                         * @description URI reference identifying this occurrence.
                         */
                        instance?: string;
                        /** @description Optional machine-readable error code from the gateway. */
                        code?: string;
                    } & {
                        [key: string]: unknown;
                    };
                    "application/json": {
                        /**
                         * Format: uri
                         * @description URI reference identifying the problem type.
                         */
                        type?: string;
                        /** @description Short human-readable summary. */
                        title?: string;
                        /** @description HTTP status code. */
                        status?: number;
                        /** @description Human-readable explanation specific to this occurrence. */
                        detail?: string;
                        /**
                         * Format: uri
                         * @description URI reference identifying this occurrence.
                         */
                        instance?: string;
                        /** @description Optional machine-readable error code from the gateway. */
                        code?: string;
                    } & {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Resource not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": {
                        /**
                         * Format: uri
                         * @description URI reference identifying the problem type.
                         */
                        type?: string;
                        /** @description Short human-readable summary. */
                        title?: string;
                        /** @description HTTP status code. */
                        status?: number;
                        /** @description Human-readable explanation specific to this occurrence. */
                        detail?: string;
                        /**
                         * Format: uri
                         * @description URI reference identifying this occurrence.
                         */
                        instance?: string;
                        /** @description Optional machine-readable error code from the gateway. */
                        code?: string;
                    } & {
                        [key: string]: unknown;
                    };
                    "application/json": {
                        /**
                         * Format: uri
                         * @description URI reference identifying the problem type.
                         */
                        type?: string;
                        /** @description Short human-readable summary. */
                        title?: string;
                        /** @description HTTP status code. */
                        status?: number;
                        /** @description Human-readable explanation specific to this occurrence. */
                        detail?: string;
                        /**
                         * Format: uri
                         * @description URI reference identifying this occurrence.
                         */
                        instance?: string;
                        /** @description Optional machine-readable error code from the gateway. */
                        code?: string;
                    } & {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Error (RFC 7807 Problem Details) */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": {
                        /**
                         * Format: uri
                         * @description URI reference identifying the problem type.
                         */
                        type?: string;
                        /** @description Short human-readable summary. */
                        title?: string;
                        /** @description HTTP status code. */
                        status?: number;
                        /** @description Human-readable explanation specific to this occurrence. */
                        detail?: string;
                        /**
                         * Format: uri
                         * @description URI reference identifying this occurrence.
                         */
                        instance?: string;
                        /** @description Optional machine-readable error code from the gateway. */
                        code?: string;
                    } & {
                        [key: string]: unknown;
                    };
                    "application/json": {
                        /**
                         * Format: uri
                         * @description URI reference identifying the problem type.
                         */
                        type?: string;
                        /** @description Short human-readable summary. */
                        title?: string;
                        /** @description HTTP status code. */
                        status?: number;
                        /** @description Human-readable explanation specific to this occurrence. */
                        detail?: string;
                        /**
                         * Format: uri
                         * @description URI reference identifying this occurrence.
                         */
                        instance?: string;
                        /** @description Optional machine-readable error code from the gateway. */
                        code?: string;
                    } & {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
}
