/**
 * Antipatterns Zod Schemas - Runtime validation schemas
 *
 * Generated by Zod Schemas Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: antipatterns
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import { makeApi, Zodios, type ZodiosOptions } from '@zodios/core';
import { z } from 'zod';

const flagAntiPattern_Body = z
  .object({
    patternType: z.enum([
      'private_data_collection',
      'encrypt_on_chain',
      'client_cert_pd',
    ]),
    proposalRef: z.string().min(1),
    fabricReference: z.string().optional(),
    networkId: z
      .string()
      .regex(/^net_[0-9A-HJKMNP-TV-Z]{26}$/)
      .optional(),
    channelId: z.string().min(1).max(128).optional(),
  })
  .passthrough();
const acceptAntiPatternRisk_Body = z
  .object({
    expiresAt: z.string().datetime({ offset: true }),
    note: z.string().max(1000).optional(),
  })
  .passthrough();

export const schemas: any = {
  flagAntiPattern_Body,
  acceptAntiPatternRisk_Body,
};

const endpoints = makeApi([
  {
    method: 'get',
    path: '/v1/anti-patterns',
    alias: 'listAntiPatternFlags',
    requestFormat: 'json',
    parameters: [
      {
        name: 'cursor',
        type: 'Query',
        schema: z.string().optional(),
      },
      {
        name: 'limit',
        type: 'Query',
        schema: z.number().int().gte(1).lte(200).optional().default(50),
      },
      {
        name: 'patternType',
        type: 'Query',
        schema: z
          .enum([
            'private_data_collection',
            'encrypt_on_chain',
            'client_cert_pd',
          ])
          .optional(),
      },
      {
        name: 'compliant',
        type: 'Query',
        schema: z.boolean().optional(),
      },
    ],
    response: z
      .object({
        data: z
          .object({
            items: z.array(
              z
                .object({
                  flagId: z.string().regex(/^apn_[0-9A-HJKMNP-TV-Z]{26}$/),
                  patternType: z.enum([
                    'private_data_collection',
                    'encrypt_on_chain',
                    'client_cert_pd',
                  ]),
                  fabricReference: z.string().optional(),
                  proposalRef: z.string().optional(),
                  networkId: z
                    .string()
                    .regex(/^net_[0-9A-HJKMNP-TV-Z]{26}$/)
                    .optional(),
                  channelId: z.string().min(1).max(128).optional(),
                  compliant: z.boolean().default(false),
                  riskAccepted: z.boolean().default(false),
                  riskAcceptanceExpiresAt: z
                    .string()
                    .datetime({ offset: true })
                    .optional(),
                  riskAcceptanceNote: z.string().optional(),
                  createdAt: z.string().datetime({ offset: true }),
                  updatedAt: z.string().datetime({ offset: true }).optional(),
                })
                .passthrough()
            ),
            nextCursor: z.string().optional(),
          })
          .passthrough(),
        meta: z
          .object({
            requestId: z.string().uuid(),
            correlationId: z.string(),
            generatedAt: z.string().datetime({ offset: true }),
          })
          .partial()
          .passthrough()
          .optional(),
      })
      .passthrough(),
    errors: [
      {
        status: 401,
        description: `Missing or invalid API key`,
        schema: z
          .object({
            type: z.string().url(),
            title: z.string(),
            status: z.number().int(),
            detail: z.string(),
            instance: z.string().url(),
            code: z.string(),
          })
          .partial()
          .passthrough(),
      },
    ],
  },
  {
    method: 'post',
    path: '/v1/anti-patterns',
    alias: 'flagAntiPattern',
    requestFormat: 'json',
    parameters: [
      {
        name: 'body',
        type: 'Body',
        schema: flagAntiPattern_Body,
      },
      {
        name: 'Idempotency-Key',
        type: 'Header',
        schema: z.string().min(1).max(128),
      },
    ],
    response: z
      .object({
        data: z
          .object({
            flagId: z.string().regex(/^apn_[0-9A-HJKMNP-TV-Z]{26}$/),
            patternType: z.enum([
              'private_data_collection',
              'encrypt_on_chain',
              'client_cert_pd',
            ]),
            fabricReference: z.string().optional(),
            proposalRef: z.string().optional(),
            networkId: z
              .string()
              .regex(/^net_[0-9A-HJKMNP-TV-Z]{26}$/)
              .optional(),
            channelId: z.string().min(1).max(128).optional(),
            compliant: z.boolean().default(false),
            riskAccepted: z.boolean().default(false),
            riskAcceptanceExpiresAt: z
              .string()
              .datetime({ offset: true })
              .optional(),
            riskAcceptanceNote: z.string().optional(),
            createdAt: z.string().datetime({ offset: true }),
            updatedAt: z.string().datetime({ offset: true }).optional(),
          })
          .passthrough(),
        meta: z
          .object({
            requestId: z.string().uuid(),
            correlationId: z.string(),
            generatedAt: z.string().datetime({ offset: true }),
          })
          .partial()
          .passthrough()
          .optional(),
      })
      .passthrough(),
    errors: [
      {
        status: 400,
        description: `Malformed request`,
        schema: z
          .object({
            type: z.string().url(),
            title: z.string(),
            status: z.number().int(),
            detail: z.string(),
            instance: z.string().url(),
            code: z.string(),
          })
          .partial()
          .passthrough(),
      },
      {
        status: 401,
        description: `Missing or invalid API key`,
        schema: z
          .object({
            type: z.string().url(),
            title: z.string(),
            status: z.number().int(),
            detail: z.string(),
            instance: z.string().url(),
            code: z.string(),
          })
          .partial()
          .passthrough(),
      },
    ],
  },
  {
    method: 'get',
    path: '/v1/anti-patterns/:flagId',
    alias: 'getAntiPatternFlag',
    requestFormat: 'json',
    parameters: [
      {
        name: 'flagId',
        type: 'Path',
        schema: z.string().regex(/^apn_[0-9A-HJKMNP-TV-Z]{26}$/),
      },
    ],
    response: z
      .object({
        data: z
          .object({
            flagId: z.string().regex(/^apn_[0-9A-HJKMNP-TV-Z]{26}$/),
            patternType: z.enum([
              'private_data_collection',
              'encrypt_on_chain',
              'client_cert_pd',
            ]),
            fabricReference: z.string().optional(),
            proposalRef: z.string().optional(),
            networkId: z
              .string()
              .regex(/^net_[0-9A-HJKMNP-TV-Z]{26}$/)
              .optional(),
            channelId: z.string().min(1).max(128).optional(),
            compliant: z.boolean().default(false),
            riskAccepted: z.boolean().default(false),
            riskAcceptanceExpiresAt: z
              .string()
              .datetime({ offset: true })
              .optional(),
            riskAcceptanceNote: z.string().optional(),
            createdAt: z.string().datetime({ offset: true }),
            updatedAt: z.string().datetime({ offset: true }).optional(),
          })
          .passthrough(),
        meta: z
          .object({
            requestId: z.string().uuid(),
            correlationId: z.string(),
            generatedAt: z.string().datetime({ offset: true }),
          })
          .partial()
          .passthrough()
          .optional(),
      })
      .passthrough(),
    errors: [
      {
        status: 401,
        description: `Missing or invalid API key`,
        schema: z
          .object({
            type: z.string().url(),
            title: z.string(),
            status: z.number().int(),
            detail: z.string(),
            instance: z.string().url(),
            code: z.string(),
          })
          .partial()
          .passthrough(),
      },
      {
        status: 404,
        description: `Resource not found`,
        schema: z
          .object({
            type: z.string().url(),
            title: z.string(),
            status: z.number().int(),
            detail: z.string(),
            instance: z.string().url(),
            code: z.string(),
          })
          .partial()
          .passthrough(),
      },
    ],
  },
  {
    method: 'post',
    path: '/v1/anti-patterns/:flagId/accept-risk',
    alias: 'acceptAntiPatternRisk',
    requestFormat: 'json',
    parameters: [
      {
        name: 'body',
        type: 'Body',
        schema: acceptAntiPatternRisk_Body,
      },
      {
        name: 'flagId',
        type: 'Path',
        schema: z.string().regex(/^apn_[0-9A-HJKMNP-TV-Z]{26}$/),
      },
      {
        name: 'Idempotency-Key',
        type: 'Header',
        schema: z.string().min(1).max(128),
      },
    ],
    response: z
      .object({
        data: z
          .object({
            flagId: z.string().regex(/^apn_[0-9A-HJKMNP-TV-Z]{26}$/),
            patternType: z.enum([
              'private_data_collection',
              'encrypt_on_chain',
              'client_cert_pd',
            ]),
            fabricReference: z.string().optional(),
            proposalRef: z.string().optional(),
            networkId: z
              .string()
              .regex(/^net_[0-9A-HJKMNP-TV-Z]{26}$/)
              .optional(),
            channelId: z.string().min(1).max(128).optional(),
            compliant: z.boolean().default(false),
            riskAccepted: z.boolean().default(false),
            riskAcceptanceExpiresAt: z
              .string()
              .datetime({ offset: true })
              .optional(),
            riskAcceptanceNote: z.string().optional(),
            createdAt: z.string().datetime({ offset: true }),
            updatedAt: z.string().datetime({ offset: true }).optional(),
          })
          .passthrough(),
        meta: z
          .object({
            requestId: z.string().uuid(),
            correlationId: z.string(),
            generatedAt: z.string().datetime({ offset: true }),
          })
          .partial()
          .passthrough()
          .optional(),
      })
      .passthrough(),
    errors: [
      {
        status: 400,
        description: `Malformed request`,
        schema: z
          .object({
            type: z.string().url(),
            title: z.string(),
            status: z.number().int(),
            detail: z.string(),
            instance: z.string().url(),
            code: z.string(),
          })
          .partial()
          .passthrough(),
      },
      {
        status: 401,
        description: `Missing or invalid API key`,
        schema: z
          .object({
            type: z.string().url(),
            title: z.string(),
            status: z.number().int(),
            detail: z.string(),
            instance: z.string().url(),
            code: z.string(),
          })
          .partial()
          .passthrough(),
      },
      {
        status: 404,
        description: `Resource not found`,
        schema: z
          .object({
            type: z.string().url(),
            title: z.string(),
            status: z.number().int(),
            detail: z.string(),
            instance: z.string().url(),
            code: z.string(),
          })
          .partial()
          .passthrough(),
      },
    ],
  },
]);

export const api: any = new Zodios(
  'https://api.ddd-codegen-starter.local',
  endpoints
);

export function createApiClient(baseUrl: string, options?: ZodiosOptions): any {
  return new Zodios(baseUrl, endpoints, options);
}
