/**
 * ListDecision DTO Factory
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: endorsement
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


import type { ListEndorsementDecisionsParams } from "@offhash/core/endorsement";

export function createListDecisionRequest(overrides: Partial<ListEndorsementDecisionsParams> = {}) {
  const raw = {
    ...overrides,
  };

  return raw;
}
