/**
 * GetScan DTO Factory
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: scans
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


import type { GetPdScanResultParams } from "@offhash/core/scans";

export function createGetScanRequest(overrides: Partial<GetPdScanResultParams> = {}) {
  const raw = {
    ...overrides,
  };

  return raw;
}
