/**
 * Factories barrel export
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: configcerts
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


/**
 * Factories Barrel Export
 *
 * Exports all entity and DTO factories for the configcerts domain.
 * Use these factories in tests to create test data.
 */

export { createConfigCertReview } from "./config-cert-review/entity/config-cert-review.entity.factory.js";
