/**
 * AcceptRiskRepository Port - Application port interface
 *
 * Generated by Port Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: antipatterns
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * AcceptRiskRepository Port
 *
 * DDD: Application port for acceptriskrepository operations.
 * This is an application-level abstraction, not a domain concept.
 * Implementations live in adapters layer.
 */

import type { AcceptAntiPatternRiskInput, AcceptAntiPatternRiskOutput } from "../dto/accept-risk.dto";
export interface AcceptRiskRepository {
  acceptAntiPatternRisk(input: AcceptAntiPatternRiskInput): Promise<AcceptAntiPatternRiskOutput>;
}

export type { AcceptAntiPatternRiskInput, AcceptAntiPatternRiskOutput } from "../dto/accept-risk.dto";
